### ISSUE TITLE
SSL version errors

### ISSUE THREAD

**Issue by codemang** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#10]
Hi, I'm getting the following errors

```
nginx | 2017/10/05 21:39:23 [error] 10#10: *12 SSL_do_handshake() failed 
(SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) 
while SSL handshaking to upstream, client: 204.9.220.42"
```

Have you seen this before

**Comment by evertramos** [comment]
Did you have it fixed? Please set up your environment for the proxy then start your web containers with setting as suggested. You should face no problem. Please update if you haven´t figure it out already.

**Comment by codemang** [comment]
@evertramos no I never managed to get it to work. I stopped working on that project due to time constraints. The error was happening on a Digital Ocean server if you want more information. Since I haven't seen other cases of this online, I'm assuming there was something wrong with my setup.

**Comment by evertramos** [comment]
Sorry to hear that... I have this settings working smothly on Digital Ocean. If you ever come to look that over let me know.
