### ISSUE TITLE
could you add a sample that uses oauth2_proxy

### ISSUE THREAD

**Issue by powerdude** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#100]
Great source you have here.  Just wondering if you've every looked at using oauth2_proxy.

**Comment by evertramos** [comment]
Hello @powerdude!

Thanks for you message. 

I believe the oauth is for another purpose of what we have here, there is a few oauth clients I have tested, keycloak, okta etc... but all of them is located behind this proxy.

The idea here is to have an automated service to start multiple apps and services in a server, which might not require any authentication such as wordpress blogs, websites etc.

But, I think oauth is a good idea for some app, and I do use them in some projects.

Not sure if this is what you mean, if now please let me know.

**Comment by powerdude** [comment]
hi @evertramos ,

Since you had an example that showed how to use basic auth, i just thought i'd ask to see if you could do another example.  I've implemented the basic auth but wanted to try to do oauth.  All the examples of using oauth2_proxy are with traefik, so it's been challenging trying to figure it out.  any ideas or pointers you could share?

**Comment by evertramos** [comment]
ohhh sorry!

yes I can help you with that.. but I will need a few days on that matter.... can you wait? 

Or you changed the subject or I miss read it....

I will see what I can do to share you something working in that matter, probably okta.

**Comment by powerdude** [comment]
yes, i can wait.  :)

**Comment by evertramos** [comment]
@powerdude,

I have implemented OAuth over our proxy... but in fact it had nothing to do with our proxy... one client (private) asked us to implement OAuth in a couple softwares running behind the onetime login, so, it worked without any special configuration in our proxy.

We have used the Laravel OAuth in the end, beacuse the of the easy setup. I can not share it (Laravel App) once I was not the developer and is was developed for the a private customer.

But, coming back to this repo, webproxy, it will pass it clean up over our proxy.

I tested okta and it did work out of the box, through our proxy, but I have not configured it in a repo with settings and everything.... sorry... really out of time now to fix things up in the new repo. 

Hope you have already got through this set up. 

Thanks!

Closing this up, if you still need it, you can reopen it.
