### ISSUE TITLE
Off Topics : Odoo 12

### ISSUE THREAD

**Issue by Tofdu31** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#101]
Hi,

I do not know how to contact you for a request, so I post my message here and am sorry.

With the services you offer (Let's Encrypt, Portainer, Nextcloud, Wordpress), I try to make Oddo 12 work by taking the examples of docker-compose.yml and .env but in the end it does not work.

Can you open a space for a solution for Odoo 12. https://hub.docker.com/_/odoo/

A very big thank you to you and sorry to the post that is not appropriate in section

Best regards

**Comment by evertramos** [comment]
You can write to:

contact@budhi.com.br
