### ISSUE TITLE
SSL cert problem

### ISSUE THREAD

**Issue by Phu-Bar** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#104]
# Error description:
Using ./test_start.sh. Accessing on port 80 is fine, I get the "It works!". But when I try to access it on port 443, I get a invalid certificate error and 500 Internal Server Error from nginx.

# Steps to reproduce
copied .env.sample to .env and changed only the NGINX_FILES_PATH.
ran ./start.sh and container starts up fine.
ran ./test_start.sh <my.domain.com>

# Expected result
http ----> "It works"
https ---> "It works"

# Error result
https ----> invalid certificate and 500 Internal Server Error

# Comments

**Comment by evertramos** [comment]
Try

```bash
./test_start_ssl.sh <my.domain.com>
```

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/test_start_ssl.sh

**Comment by Phu-Bar** [comment]
Hi evertramos,

I tried that and it still gave the same problem. I started from fresh again and still nothing. Tried clearing cache on different browsers.

**Comment by evertramos** [comment]
Hello @Phu-Bar 

Do you have your dns pointing out to your public ip address?

**Comment by evertramos** [comment]
can you post your .env file please

**Comment by evertramos** [comment]
Also check your logs on letsencrypt container and post as well, please:


```bash
docker logs nginx-letsencrypt
```
