### ISSUE TITLE
multiple port encripted like 443 and 8080

### ISSUE THREAD

**Issue by HeeroYui** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#105]
# Error description:
simple test work correctly, but when I try to change the port of the interacting website (for an administration site with https), I can not access to the site

# Steps to reproduce
replace in the test_start_ssl.sh the line:
```
docker run -d -e VIRTUAL_HOST=$DOMAIN -e VIRTUAL_PORT=8080 -e LETSENCRYPT_HOST=$DOMAIN --network=$NETWORK -p 8080:80 --name $NAME httpd:alpine
```

# Expected result

a webpage accessible with the adresse: https://$DOMAIN:8080

# Error result
no page availlable

# Comments

**Comment by evertramos** [comment]
Hello @HeeroYui,

Thanks for your message.

If you are using the option `-p 8080:80` and in the browser **https://$DOMAIN:8080** you are not passing through the proxy... so you might don´t need it.

If you want to use the proxy just try the **https://$DOMAIN*** using the same configuration you have in your `docker-compose up -d...`, you could even remove the `-p` option.

**Comment by evertramos** [comment]
Once we did not have a reply we will assume that you have solved it.
