### ISSUE TITLE
Patch to nginx template to allow successful LE initial challenge

### ISSUE THREAD

**Issue by cryxia** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#11]
Hello!

I used your compose scripts but I was having some trouble getting subdomains to work correct all the time - especially during the intial setup although because of some quirk of the nginx setup it worked correctly afterwards...

I made a pull request to the original nginx template that you may be interested in patching in:
https://github.com/jwilder/nginx-proxy/pull/943

**Comment by evertramos** [comment]
Thank you very much! I will test it and get it updated.

Cheers!

**Comment by evertramos** [comment]
@cryxia Thanks for sharing, once we've updated the *run* script to download the latest version of `nginx.tmpl` file we will wait for @jwilder to get it passed. Thanks again!!!
