### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG. error on multiple domains

### ISSUE THREAD

**Issue by pumppi** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#111]
# Error description:
SSL_ERROR_RX_RECORD_TOO_LONG.

I get error messages some times with Firefox for SSL_ERROR_RX_RECORD_TOO_LONG. When requesting url. Docker automaticly solves the issue in few minutes, but still it takes few minutes.

I use these setups in docker-compose.yml
- VIRTUAL_HOST=api.xxx.com
- LETSENCRYPT_HOST=api.xxx.com
- LETSENCRYPT_EMAIL=info@xxx.com

# Steps to reproduce
At the moment, I'm not sure how to reproduce issue. I try to reproduce it. 

# Expected result
No errors when accessing to domain

# Error result
SSL_ERROR_RX_RECORD_TOO_LONG.
(https://www.namecheap.com/support/knowledgebase/article.aspx/807/2238/firefox-error-code-sslerrorrxrecordtoolong)

# Comments

**Comment by pumppi** [comment]
When I try to add external ip to settings. I get 

```
Error starting userland proxy: listen tcp IP:443: bind: cannot assign requested address

ERROR: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (1b2f72fdb0ec9f7754ec7432464ad64deb7ec3a1f1242303bffaf328f09d2144): Error starting userland proxy: listen tcp IP:443: bind: cannot assign requested address
ERROR: Encountered errors while bringing up the project.
```
Is this the cause?

**Comment by evertramos** [comment]
Hello @pumppi,

Did you set your IP address to it? Never seen this error... what are the logs says? Can you post your logs from gen/web/letsencrypt containers?

**Comment by pumppi** [comment]
Hi, 

I get this kind of errors in nginx-web container when the issues occurs. 

`2018/12/03 13:10:37 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/x.domain.com.crt"
2018/12/03 13:11:16 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/api.x.domain.com.crt"
2018/12/03 13:16:04 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/api.y.domain.com.crt"
2018/12/03 13:19:26 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/api.a.domain.com.crt"
2018/12/03 13:19:26 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/b.domain.com.crt"
2018/12/03 13:22:06 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/a.domain.com.crt"
2018/12/03 13:22:08 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/api.a.domain.com.crt"
2018/12/03 14:00:23 [warn] 30#30: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/integration.x.domain.com.crt"`

**Comment by pumppi** [comment]
Logs contains only these kind of messages:

`2018-11-26 22:29:49,015:INFO:simp_le:1564: Certificates already exist and renewal is not necessary, exiting with status code 1.
/app
/etc/nginx/certs/x.domaincom /app
Creating/renewal x.domain.com certificates... (x.domain.com)
/app`

The log file is full of those.

**Comment by evertramos** [comment]
Well sorry not being able to help... seems ok and I never faced this issue... please try to contact lets encrypt to see if they know something about it.

**Comment by pumppi** [comment]
Hi,

I found this kind of thread. 
https://community.letsencrypt.org/t/no-resolver-defined-to-resolve-ocsp-int-x3-letsencrypt-org-while-requesting-certificate-status-responder-ocsp-int-x3-letsencrypt-org/21427

**Comment by evertramos** [comment]
I am not sure if this is related to the proxy itself... is your domain really long? What is your domain name?

**Comment by evertramos** [comment]
This logs is shown on my services as well but does have this error when accessing the url in the browser....

**Comment by evertramos** [comment]
Closing this issue...
