### ISSUE TITLE
Synology port mapping

### ISSUE THREAD

**Issue by Seennt** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#115]
# Error description:
I'm trying to install "docker-compose-letsencrypt-nginx-proxy-companion" on my synology NAS.

# Steps to reproduce
My network setup is like: Router(Public IP) -> NAS(Local IP). My router provides me a virtual server option, so i can map a public port to an alternative local port E.g. 34.34.34.34:80 -> 192.168.0.1:81. 

The same holds for https(443).

Within docker-compose(env file)
      - "192.168.0.1:81:80"
      - "192.168.0.1:81:443"

# Expected result
I assume the circumvent the in used port 80, 443. and http-01 challenge will work. 

# Error result
Google chrome privacy error! can't reach my the site and no padlock([nopadlock](https://www.whynopadlock.com/ )). tells me something regarding "invalid intermediate"

# Comments
What am i missing?  I have red the [howto](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/docs/HOWTO-Synlogy.md), but i'm a bid confused.  Do you mean port forward(at router) and create a port mapping on my NAS? How can i achieve such a mapping on my NAS?

Thanks in advance,

**Comment by evertramos** [comment]
Closing this issue since we haven´t received any further comments.
