### ISSUE TITLE
Rename conf.d to conf.d.sample?

### ISSUE THREAD

**Issue by fracz** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#117]
Hi there.

Really appreciate the idea of custom server configuration. However, the default `conf.d` directory is already there. Any change in these files makes Git angry about not clean working area.

Wouldn't be a better idea to make it `cond.d.sample` and require to copy it to `conf.d` afer enabling the `USE_NGINX_CONF_FILES` env? `cond.d` should be added to `.gitignore`.

**Comment by evertramos** [comment]
Hello @fracz,

Thanks for your comments, but I don´t like the idea... I think it´s better this way.
