### ISSUE TITLE
Cannot configure with Tuleap

### ISSUE THREAD

**Issue by mareeba** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#12]
Am not having any luck getting this to work with:
https://github.com/Enalean/docker-tuleap-aio

Is there any chance you could show me an example docker-compose.yml that might work?

**Comment by evertramos** [comment]
You must separate your environment... keep this settings up (https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) and then create a new container with or compose file with your new environment as of wordpress site (https://github.com/evertramos/wordpress-docker-letsencrypt) but remenber to keep it all in the same network settings.

**Comment by mareeba** [comment]
Okay, I have managed to get the nginx-proxy-companion container up and working (following [https://blog.mathewmerrick.com/2017/09/19/docker-nginx-letsencrypt-ghost/]).

I then tested this with the ghost example (via docker-compose) and was able to access it successfully on the remote vps without issue. Note that I had to specify a version 2 compose file instead of version 3.

I then followed your instructions above (substituting the correct domains and email address) and this built successfully and was visible and running via `$ docker ps -a`

However when I visit the specified domain on my local machine I receive a "502 Bad Gatweay" nginx message??

Any suggestions?? Any chance you could perhaps try and replicate perhaps?

**Comment by mareeba** [comment]
I also tried using this docker-compose file which also built and ran successfully but led to the same 502 error as your suggested method.

`version: '2'
services:
  tuleap:
    image: enalean/tuleap-aio
    restart: always
    volumes:
      - ./tuleap-data:/data
    environment:
      VIRTUAL_HOST: tuleap.cookeinternational.com.au
      LETSENCRYPT_HOST: tuleap.cookeinternational.com.au
      LETSENCRYPT_EMAIL: mikecooke.secure@gmail.com

networks:
  default:
    external:
      name: webproxy
`

**Comment by evertramos** [comment]
I got the problem, but must take some time to fix it. 

The point is that your tuleap apache is not working... our enviorment it´s fine. Log in into your container:

`docker exec -it <container_name> bash` 

and check 

`service httpd status` 

In order to work you must do 

`yum update`

But still, you must make your apache see the correct ssl certificate, so you should mount your nginx certificate for your domain `my.domain.tld` into your apache's certs folder in you tuleap container.

I have not tested, but could try later on next week, leaving now for a trip and will be back on Tuesday, sorry for that...

But you should be fine, if not, let me know I can help you out with that matter.

Cheers!

**Comment by mareeba** [comment]
Thanks for your kind assistance!

Have managed to get everything setup as per above, however is appears that the issue is with the certificates not being generated (or generated in the correct directory?). 

When I attempt to start apache I get the following error:
```
Starting httpd: Syntax error on line 66 of /etc/httpd/conf.d/tuleap-vhost.conf:
SSLCertificateFile: file '/certs/<redacted.mydomain.tld>.crt' does not exist or is empty
[FAILED]
```

Please note that the directory structure for/location of the configuration files appear to be different when using the docker setup:
[https://tuleap.net/pipermail/tuleap-devel/2016-July/004758.html](url)
```
>> the normal installation (or maybe it's because i came from an older
>> installation ?)
>>
>> The main configuration file is /etc/http/conf.d/tuleap-vhost.conf
>>
>> And in my normal installation from rpm, it was, all in the main :
>> /etc/http/conf/httpd.conf
```

When I inspect `/certs` within the tuleap container:
`$ docker exec -it tuleap-production ls /certs/`


I can only see the following:
```
4 drwxr-xr-x 3 root root 4096 Oct 19 09:11 ./
4 drwxr-xr-x 1 root root 4096 Oct 19 09:11 ../
4 -rw-r--r-- 1 root root  424 Oct 19 08:59 dhparam.pem
4 drwxr-xr-x 2 root root 4096 Oct 19 09:11 <redacted.mydomain.tld>/
```

and `/certs/<redacted.mydomain.tld>/` is empty!

Any thoughts?

**Comment by evertramos** [comment]
You are mounting the wrong folder... you must mount in your Tuleap container the correct path to your certificate as of web proxy which has the simlink to the certificates generated by letsencrypt container. After that you must correct the apaches file in you host which is located in ./tuleap-data/etc/httpd/conf.d/ so please restart your project very slow and calm and you should be fine. I am by cellphone now and will be off a couple days. Hope you get through. I got it running at https://tileap.budhi.com.br yesterday so it works. Just start over in a clean environment. Will close this issue but you can still reply on it. I will check over next week. Cheers!

**Comment by mareeba** [comment]
Thanks! Still a bit unclear about what the correct path is (in the Tuleap container)?

**Comment by evertramos** [comment]
@mareeba,

When you write:

"and /certs/<redacted.mydomain.tld>/ is empty!" this should not be a folder....

If you follow the steps I describe you will get through very easy. I do not even know what tuleap is what it does, but it just worked fine in my server.

On the step **1** as I described there is a line:

`- /path/to/your/nginx-letsencrypt/certificates:/certs`

This line should be referenced as in your config file of your proxy:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/.env.sample

Which should be mounted  as of below:

if you _.env_ file is:

`NGINX_FILES_PATH=/home/mareeba/nginx/data`

In your docker-compose file for tuleap should be:

`- /home/mareeba/nginx/data/certs:/certs`

This is it for the step 1.

To config the Apache file, in the same path of your docker-compose file for the Tuleap container, after setting up step 1, and running a `docker-compose up -d`, you must find the folder `tuleap-data`, which you will find the following path, assuming you has a tuleap path with you compose file (`/home/mareeba/tuleap/`) in your home:

`/home/mareeba/tuleap/tuleap-data/etc/httpd/conf.d/tuleap-vhost.conf`

This file must be updated as step 2 of my post above.

After that you restart your container doing the following:

`docker-compose down`

and 

`docker-compose up -d`

You access your container and start apache, which for some reason it´s not starting, please contact tuleap developer.

You do:

`docker -it run tuleap-production bash`

And do:

`service httpd start`

You are ready to go!

If even though you can not get it up and running, please start over a couple times, remove all old folders of tuleap, remove images and everything and start again, even though you can not fix it, read some docs of docker to get more familiar with it and tuleap container, which I myself do not know what this is.

**Comment by evertramos** [comment]
Did you manage to get it running?

**Comment by evertramos** [comment]
The correct url is:

https://tuleap.budhi.com.br/

**Comment by mareeba** [comment]
Got it working now! Thank you very much indeed!!
