### ISSUE TITLE
Production Mail server

### ISSUE THREAD

**Issue by Kubilai12** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#120]
Hi do you make test for add mail server into this production environnement ?

**Comment by evertramos** [comment]
Hello @Kubilai12,

I have not implemented a mail server behind this proxy... but should follow the same settings of any other service, adding the `VIRTUAL_HOST` environment to the container and you will get the web interface through the proxy.

**Comment by Kubilai12** [comment]
How can i do with this one : 

`
version: "3"

services:
  rainloop:
    image: hardware/rainloop
    links:
      - mail
    volumes:
      - ./data/rainloop:/rainloop/data

  mail:
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./data/mail/data:/var/mail
      - ./data/mail/state:/var/mail-state
      - ./mail/config:/tmp/docker-mailserver/
      - ./data/entry/acme/acme-v01.api.letsencrypt.org/sites/mail.fancydomain.tld:/tmp/ssl:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_MANAGESIEVE=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/mail.fancydomain.tld.crt
      - SSL_KEY_PATH=/tmp/ssl/mail.fancydomain.tld.key
    cap_add:
      - `NET_ADMIN
`
`
