### ISSUE TITLE
conf files are not copied

### ISSUE THREAD

**Issue by DaniSchenk** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#122]
# Error description:
I'm facing the problem, that my `conf.d/*.conf` files are not being copied to `data/conf.d/`.
- `.env` variable is set: `USE_NGINX_CONF_FILES=true` and `NGINX_FILES_PATH=./data/`
- script starts with `sudo ./start.sh`
- running `start.sh` as root has no positive effect
- `conf.d/` is not empty
- it's the only problem I have, all other thing are running as expected

I'm testing my nginx config with: `sudo docker exec nginx-web nginx -T`.
I had to copy all custom configs manually to the data folder. After that everything works fine. I've seen that the `start.sh` throws error messages, if the copy process fails, but I'm not getting these errors. Maybe someone can help me with this...

**Comment by evertramos** [comment]
Hello @DaniSchenk,

Thanks for using it!

Where are you conf.d folder located? Did you keep it in the same folder of the start script?

**Comment by evertramos** [comment]
@DaniSchenk I have tested this over and over to see if there is any errors, and I have ever faced this issue... so, I would recommend you start new environment, clean up the files already downloaded and fire the start script again, from the scratch. You will see that it works! Are you using Linux? Whats your kernel version? Please try to run that on Ubuntu LTS and see this working! Hope you have already gone through it. I will close this as I could not replay this issue, but we can continue discussing it.

**Comment by DaniSchenk** [comment]
@evertramos I found my mistake! 🙌
Problem was my DOS line ending. I just had to change vom `CLRF` to `LF` and everything worked as expected! Maybe this helps someone...

**Comment by evertramos** [comment]
@DaniSchenk 

Thank you very much for sharing! Sure someone will need it.
