### ISSUE TITLE
UWSGI pass though

### ISSUE THREAD

**Issue by samip5** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#125]
# Error description:
Unable to access UWSGI container.

# Steps to reproduce
Create a UWSGI container with app running
set port to 80
set ENV variables
Start the container and wait for letsencrypt to do it's thing.
Access the url specified.

# Expected result
I'm able to access it normally.

# Error result
The UWSGI container is only saying: `invalid request block size: 21573 (max 4096)...skip`

# Comments
The nginx.tpl has a UWSGI thing, but how do I set it to use that one?

**Comment by evertramos** [comment]
Did you start this proxy and tested with a domain as in the readme?

I think this is not related to this repo... how does your compose files look like?

**Comment by samip5** [comment]
The issue was to do with uwsgi not accepting HTTP connections by itself, it was expecting a socket connection to itself.

The fact that it's using `proxy_pass` and not` uwsgi_pass` is the problem.

**Comment by evertramos** [comment]
ok so post this issue in @jwilder repo.

Thanks!
