### ISSUE TITLE
ftp or ftps

### ISSUE THREAD

**Issue by Elmit2015** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#126]
I installed:
1. git clone https://github.com/evertramos/docker-wordpress-letsencrypt.git and setup my web site
2. git clone https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.git

It works fine! ;-) Thanks a lot!!!

I login to my wordpress site, and try to add contactform 7 and pagebuilder. However, both require a connection ftp or ftps. How do I add this into that system?

I tried to add a user and the invitation email is not sent. What do I need to do to get that to work?

**Comment by Elmit2015** [comment]
I fixed that by chown www-data:www-data of wp-content directory.

Mail I could not fix yet. Any hint?

**Comment by evertramos** [comment]
I still have not looked to the emails... if you find a solutions please come back.
