### ISSUE TITLE
Question How to add other domain to existant container ?

### ISSUE THREAD

**Issue by Kubilai12** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#128]
I ran a container with this way : 

docker run -d -e VIRTUAL_HOST=your.domain.com \
              -e LETSENCRYPT_HOST=your.domain.com \
              -e LETSENCRYPT_EMAIL=your.email@your.domain.com \
              --network=webproxy \
              --name my_app \
              httpd:alpine

And now i want to add "**_your.domain2.com_**"  to the same container.

Is it possible ? How can i do ?

Thanks

**Comment by evertramos** [comment]
Hello @Kubilai12,

You must stop your container and restart with this domain in your environment... sometime takes a couple hours to finish the new certificate, but should work.

Please advise.

**Comment by evertramos** [comment]
It seems you have solved this right? Closing...
