### ISSUE TITLE
Prevent listening to port 443 (https) for specific hosts

### ISSUE THREAD

**Issue by Fensterbank** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#131]
If I create a new entry in my own docker-compose, the autogenerated `nginx-data/conf.d/defaul.conf` will be updated.
But it seems a 443 entry is always generated, even if I did not specify `LETSENCRYPT_HOST`.

How is it possible to create a http only page, which does not listen to port 443 (and therefore create a certificate error)?

**Comment by evertramos** [comment]
Hello @Fensterbank,

Please try to add the following:

```bash
HTTPS_METHOD=nohttp
```

As of https://github.com/jwilder/nginx-proxy#how-ssl-support-works

**Comment by evertramos** [comment]
closing... since we had no reply on that...
