### ISSUE TITLE
Block direct access to host ip

### ISSUE THREAD

**Issue by teminvictus** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#132]
hi, maybe off topic.
containers and reverse proxy working perfectly. question so, is it possible to block the access to the host ip. 

meaning, when I type in my servers ip I land on the page 503. (service Temporarily Unavailable)
possible to block or redirect it?

thanks

**Comment by evertramos** [comment]
Hello @teminvictus,

Try to add the following:

```bash
DEFAULT_HOST=foo.bar.com
```

As of https://github.com/jwilder/nginx-proxy#default-host

**Comment by evertramos** [comment]
It seems this might helped you out right? closing...

**Comment by codex-corp** [comment]
@teminvictus can you please guide me where to add it `DEFAULT_HOST` ?
