### ISSUE TITLE
How to investigate issues

### ISSUE THREAD

**Issue by LuxoftAKutsan** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#133]
After I get everything works with couple of services, in couple of hours I am having an error : 
503 Service Temporarily Unavailable on one of them, and warning about invalid certificated.
I would like to investigate where is the problem.

How can I read nginx logs? app logs, letsencrypt logs?

Where can I get forwarding rules for domain names in in nginx proxy.

**Comment by evertramos** [comment]
Hello @LuxoftAKutsan, 

Please read Docker documentation (https://docs.docker.com/) to understand Docker Environment a little better.

To git you a heads up you can try:

```bash
$ docker logs nginx-web
$ docker logs nginx-letsencrypt
```

Cheers!
