### ISSUE TITLE
Update nginx.tmpl or add it to gitignore

### ISSUE THREAD

**Issue by psykora** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#134]
I propose to add `nginx.tmpl` to `.gitignore` as it is anyway downloaded with `./start.sh`.

I think that at least it should be updated to latest version from original repository as I almost proposed a merge request for it before noticing that `./start.sh` is already updating it.

Thanks,
Peter.

**Comment by psykora** [comment]
Created branches for both alternatives:
* **gitignore** (preferred): https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/compare/master...psykora:chore-gitignore_nginx_tmpl?expand=1

* or **update**: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/compare/master...psykora:fix-hsts_with_no_redirect?expand=1

**Comment by evertramos** [comment]
Hello @psykora,

Thanks for your comments. In fact the "update" you should send it to @jwilder once he owns the template. 

I wouldn´t like to remove it from our repo because I always update it when it has some specific changes and never know when it will be gone... so we better keep it in our repo as well.

**Comment by psykora** [comment]
Hi @evertramos,

Actually I did not propose any changes to @jwilder's version, just the `nginx.tmpl` in this repo is outdated in compare to his repo. That's the reason why I would rather remove it as it is difficult to keep it up to date.

But you are to decide, if you want to keep it, may I at least propose to update it to latest version? (as in the [**update**](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/compare/master...psykora:fix-hsts_with_no_redirect?expand=1) link I mentioned above). The nginx.tmpl is downloaded directly from jwilder's repo so there are no other changes.

Thanks for understanding,
Peter.

**Comment by evertramos** [comment]
I will update it. Thanks!

**Comment by evertramos** [comment]
done!
