### ISSUE TITLE
MySQL Connections not secure inside PHPMyAdmin Docker

### ISSUE THREAD

**Issue by chharish** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#135]
# Error description:
I have successfully deployed a phpMyAdmin interface with SSL. but the SQl server connections are not going through a secure connection. I know the native way to setup secure connection from the command line, but not sure how I can give a command like "mysql -h only-ssl-db.ct5b4uz1gops.eu-central-1.rds.amazonaws.com --ssl-ca=/var/mysql-certs/rds-combined-ca-bundle.pem --ssl-mode=REQUIRED -u onlyssldbusr -P 3306 -p" to the docker container. 

Is there a way we can use SSL to encrypt a connection from our docker running a web application to an external DB server running MySQL?

**Comment by evertramos** [comment]
Hello @chharish ,

Thanks for your message.

Sure there is a way to secure the connection... but don´t know what this issue has to do with the proxy...

Is there anything related with this repo?

Thanks!

**Comment by chharish** [comment]
I was hoping this could be a feature enhancement for this docker to also cover SSL for SQL connections. But I could be wrong, my apologies if this out of scope. The repo works fine, Thanks for all the hardwork

**Comment by evertramos** [comment]
Hello @chharish,

I didn´t mean to be rude... just asked if you thinkg there were anything related to this repo... I use phpmyadmin and the connection is secured, once the proxy does the secure part and it forwards the connection to the phpmyadmin container, but accessing the local database containers, so it does not go on the web. 

If you want to try this connection might be need to add the url ssl certificate generated by this proxy to your phpmyadmin to your phpmyadmin container. You might mount the folder with the ssl certificate which is located at the folder **/certs** in your proxy data. Mounting this cert in the container you might will be able to secure the connection to your external database. I never try that, just a suggestion, ok?

Take care!
