### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by chrisckc** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#136]
A couple of minor improvements / changes depending on usage

**First suggstion:**
When using the real_ip module, it is a good idea to modify the "X-Forwarded-For" directive in nginx.tmpl
instead of:
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
use:
proxy_set_header X-Forwarded-For '$http_x_forwarded_for, $realip_remote_addr';

Reasoning:
The var "$proxy_add_x_forwarded_for" is equal to "$http_x_forwarded_for,$remote_addr" and when using the real_ip module, $remote_addr is updated using values from X-Forwarded-For resulting in potential loss of information at upstream receiving end.

Affects:
When using the real_ip module, if there is a load balancer or another proxy in front of nginx which sets the "X-Forwarded-For" header, the ip seen by the nginx proxy is not added to the "X-Forwarded-For" header as it should be, instead the substituted value in $remote_addr is used. The $realip_remote_addr var contains the original value of $remote_addr when using the real_ip module, so it makes sense to use that to preserve the correct chain of ip addresses.

Symptoms:
I spotted this when trying to figure out why i had the same ip listed twice in "X-Forwarded-For", this happens when a proxy in front of nginx is set as trusted (listed in set_real_ip_from)
The reason for the duplication is because $remote_addr is updated by real_ip module to match the ip of the trusted proxy by inspecting "X-Forwarded-For" , the updated ip is then added to the end of "X-Forwarded-For" chain, which already contains the same ip.

**Second suggestion:**
Reduce generated outbound network traffic from junk incoming traffic by changing nginx.tmpl to return 444 status code instead of 503 for unknown host headers.
"444 is a non-standard status code used to instruct nginx to close the connection without sending a response to the client"

**Third suggestion, maybe?**
Most config recommendations suggest using:
proxy_cache_bypass $http_upgrade;
which is not part of the config, not sure it its really required, this config directive is only in affect when connection upgrade is sent and WebSockets can't be cached anyway.

The second and third suggestions are obtained from recommendations here:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2

**Comment by evertramos** [comment]
Agree with everything! 

But these suggestions must be made in the nginx.tmpl "owner" which is:

https://github.com/jwilder/nginx-proxy

So, please got ahead and post this suggestions on his page. Thanks!
