### ISSUE TITLE
No resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org

### ISSUE THREAD

**Issue by ratio91** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#139]
# Error description:
_No resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org_

# Steps to reproduce
letsencrypt updated, restarted, same error

# Expected result
should resolve the address

# Error result
can not renew certificates

# Comments

**Comment by evertramos** [comment]
Post on [https://github.com/jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy), but this is not happening on my side... Try to update the nginx template.
