### ISSUE TITLE
Let nginx proxy several ports for a subdomain.

### ISSUE THREAD

**Issue by GijsVermarien** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#140]
# Error description:
I tried to install the gitlab-ce edition, which uses ports: 22, 80 and 443. But I cannot get this to work with all the ports. This is logical as there is only one virtual port variable, but in order for gitlab to work properly all ports are needed.

# Steps to reproduce
 sudo docker run --detach \
 --hostname git.mydomain.com \
 --publish 3443:443 --publish 3380:80 --publish 3322:22 \
 --name gijslab \
 --restart always \
 --env "VIRTUAL_PORT=3443" \
 --env "VIRTUAL_PORT=3380" \
 --env "VIRTUAL_PORT=3322" \
  --volume /srv/gitlab/config:/etc/gitlab \
  --volume /srv/gitlab/logs:/var/log/gitlab \
  --volume /srv/gitlab/data:/var/opt/gitlab \
  -e VIRTUAL_HOST=git.mydomain.com \
  -e LETSENCRYPT_HOST=git.mydomain.com \
  -e LETSENCRYPT_EMAIL=myemail@gmail.com \
      gitlab/gitlab-ce:latest

# Expected result
All the ports being forwarded on the subdomain, which it does not unfortunately.

**Comment by GijsVermarien** [comment]
I just simplified the script so it would only do https over port 3443, but this unfortunately does not work either, I also added the webproxy directly in order to not forget it.
` sudo docker run --detach \
 --hostname git.mydomail.com \
 --publish 3443:443 --publish 3322:22 \
 --name gijslab \
 --restart always \
 --volume /srv/gitlab/config:/etc/gitlab \
 --volume /srv/gitlab/logs:/var/log/gitlab \
 --volume /srv/gitlab/data:/var/opt/gitlab \
 --env VIRTUAL_PORT=3443\
 -e VIRTUAL_HOST=git.mydomail.com \
 -e LETSENCRYPT_HOST=git.mydomail.com \
 -e LETSENCRYPT_EMAIL=myemail@gmail.com \
 --network=webproxy \
      gitlab/gitlab-ce:latest
`

**Comment by evertramos** [comment]
Hello @GijsVermarien,

You can keep the port 22 binded to your host if this is the case.. and for the port 80 or 443 you don´t need to "publish" the gitlab port... if you check the readme the "virtual_port" should only be used if you don´t have the default port available.. so try this:

```bash
sudo docker run --detach
--hostname git.mydomail.com
--publish 3322:22
--name gijslab
--restart always
--volume /srv/gitlab/config:/etc/gitlab
--volume /srv/gitlab/logs:/var/log/gitlab
--volume /srv/gitlab/data:/var/opt/gitlab
-e VIRTUAL_HOST=git.mydomail.com
-e LETSENCRYPT_HOST=git.mydomail.com
-e LETSENCRYPT_EMAIL=myemail@gmail.com
--network=webproxy
gitlab/gitlab-ce:latest
```

Let me know how it goes.
