### ISSUE TITLE
Restrict access to one server

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#142]
Hi,
thank you for your work. I was wondering, if it is possible to restrict access to one server to only local IPs. 
My setup would than be an additional openvpn server, so I could dial in the local network and access it.

Thanks
Jan

**Comment by pgassmann** [comment]
What do you mean by local network? localhost? or private network range?

You can configure the `IP=` in your .env to listen only on a localhost address `127.0.0.1`

If you do that, you cannot use letsencrypt to get ssl Certificates as the challenge requires that the webserver is reachable from the Internet.

Other restrictions are possible with Firewalling, but that is not part of this project.

**Comment by evertramos** [comment]
Since no reply we will close it...
