### ISSUE TITLE
[Question] nginx:alpine for nginx-web container

### ISSUE THREAD

**Issue by AlexBroadcast** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#143]
Hello friends,

I would like to know if there is any known problem for which the image `nginx:alpine` has not been used for the `nginx-web` container, especially when `jwilder/docker-gen` uses it in its Dockerfile.

In my tests it works well and the image uses less space on the disk.

Thank you.

**Comment by evertramos** [comment]
Hello @AlexBroadcast!!!

In fact, there is no specific reason.... 45mb in the original nginx... but should work ok with alpine.

We might add an option in the script.

Thank you.

**Comment by AlexBroadcast** [comment]
Thanks for your work, @evertramos!
