### ISSUE TITLE
Doesn't work when using Docker Stack and Docker Swarm

### ISSUE THREAD

**Issue by rwatts3** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#145]
There is an environment variable on the nginx-letsencrypt service called
`NGINX_PROXY_CONTAINER` unfortunately because i'm deploying this to a docker swarm cluster I do not know the name and cannot specify the name of the service container.

This also causes the command in nginx-gen -notify-sighup to fail because it's looking for a specific container name.

**Comment by evertramos** [comment]
This repo does not work with docker-swarm... it´s for single server... you could use swarm to connect networks between server, but in regular mode you will not be able to use it with swarm.

**Comment by j7an** [comment]
@rwatts3 If you absolutely need Swarm or something similar you can try the following:

- [Docker Flow Proxy](https://github.com/docker-flow/docker-flow-proxy)
- [tsuru](https://github.com/tsuru/tsuru)
- [Flynn](https://github.com/flynn/flynn)
- [traefik](https://github.com/containous/traefik)
