### ISSUE TITLE
Change index

### ISSUE THREAD

**Issue by lucasbulow** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#146]
# Error description:
Cant find path to change index.html
I want to change page of "It Works"
# Error result
http://prntscr.com/ngwyxz

**Comment by evertramos** [comment]
Dear @lucasbulow,

This issue has nothing to do with the proxy... the "it works" is realted to the container you started along with the proxy... so, please start looking into your container you have started which probably is realted to this proxy.

Give some look at the docker docs and do some tests there before starting looking into proxies and those kind of things. Try to ran a stand alone container and see how it works first. You will get there sooner than you think.

Hands on!

Good Luck!

**Comment by lucasbulow** [comment]
thank you.
