### ISSUE TITLE
Executable File not found in $PATH

### ISSUE THREAD

**Issue by notacompletemoron** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#148]
Hi, I followed your guides to a T, but am still having some trouble. Can you please help?

# Error description:
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"nginx\": executable file not found in $PATH": unknown

# Steps to reproduce
Install compose YAMLs based on guides?

# Expected result
Working Dockers based on guides!

# Error result
USER@Minecraft-01:~$ docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
04177efe0d57        wordpress:latest                         "docker-entrypoint.s…"   17 hours ago        Up 17 hours         0.0.0.0:8080->80/tcp                       wordpress
e068454ad777        phpmyadmin/phpmyadmin                    "/run.sh supervisord…"   17 hours ago        Up 17 hours         9000/tcp, 0.0.0.0:8181->80/tcp             fskay_pma_1
c58b69db160d        mariadb:latest                           "docker-entrypoint.s…"   17 hours ago        Up 17 hours         3306/tcp                                   db
573977fa0d90        jwilder/docker-gen                       "/usr/local/bin/dock…"   10 days ago         Up 17 hours                                                    nginx-gen
cdf7a069fe50        nginx                                    "nginx -g 'daemon of…"   10 days ago         Up 17 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-web
d330ecf1c626        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   10 days ago         Up 17 hours                                                    nginx-letsencrypt
USER@Minecraft-01:~$ docker exec -it nginx-letsencrypt nginx -s reload
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"nginx\": executable file not found in $PATH": unknown

# Comments
I can get to phpMyAdmin, and my Wordpress instance with local IP, but my LE SSL cert is still failing, and can't access via URL.

**Comment by evertramos** [comment]
Are you on Linux? 

You don´t need to restart the containers in order to work... Your container seems to be working for the last 10 days... 

Did you set up your wordpress in the same network of the proxy? Did you set up the VIRTUAL_HOST, LETSENCRYPT_HOST environment variables? 

Please check this repo below as an example:

https://github.com/evertramos/docker-wordpress-letsencrypt

Wait your comments.

**Comment by notacompletemoron** [comment]
I did the restart to get those messages. Otherwise, I was in the dark as to why it's failing.

I should have. Lemme double check the env files.

.env for my Wordpress instance;

`#
# Network name
#
# Your container app must use a network conencted to your webproxy
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
#
NETWORK=webproxy`

.env for my nginx companion;

`#
# Default Network
#
NETWORK=webproxy`

I am a little confused about this bit though;

`#
# Set the IP address of the external access Interface
#
IP=0.0.0.0`

What should I put there?

**Comment by evertramos** [comment]
What does your log says?

`$ docker logs nginx-letsencrypt `

**Comment by notacompletemoron** [comment]
```
Debugging tips: -v improves output verbosity. Help is available under --help.
/etc/nginx/certs/fskay.net
Sleep for 3600s
/etc/nginx/certs/fskay.net /etc/nginx/certs/fskay.net
Creating/renewal fskay.net certificates... (fskay.net www.fskay.net)
2019-05-14 13:07:06,833:INFO:simp_le:1479: Generating new certificate private key
2019-05-14 13:07:07,588:ERROR:simp_le:1446: CA marked some of the authorizations                                                                                                                                                       as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider                                                                                                                                                       does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-01.api.letsencrypt.org/acme/authz/RANDOM_STRING
Challenge validation has failed, see error log.
```

I don't understand. My DNS is the same as it was. I didn't touch my UFW, or NAT settings.

**Comment by evertramos** [comment]
Are you on Linux?

**Comment by evertramos** [comment]
It seems you already have a certificate before... did you set it using the proxy before?

this is not a proxy bug... try to add a subdomain, such as wp.fskay.net, you will see it will work...
