### ISSUE TITLE
[nginx-web] - bind: cannot assign requested address

### ISSUE THREAD

**Issue by Guiraud** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#149]
# Error description:
error message :  "Error starting userland proxy: listen tcp 51.15.210.18:443: bind: cannot assign requested address"

# Steps to reproduce
./start.sh on a brand new vps

# Expected result
docker containers on

# Error result : 
 Error starting userland proxy: listen tcp 51.15.210.18:443: bind: cannot assign requested address
# Comments
I get after updating .env and launching start.sh : 
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16292  100 16292    0     0  74772      0 --:--:-- --:--:-- --:--:-- 75078
Pulling nginx-web         ... done
Pulling nginx-gen         ... done
Pulling nginx-letsencrypt ... done
Premère option
Starting nginx-web ...
nginx-letsencrypt is up-to-date
Starting nginx-web ... error

ERROR: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (a1476bc8e02ba57bf1c3639cca112f12b20e42071eb9e15f62e4e6a25dd47f3d): Error starting userland proxy: listen tcp 51.15.210.18:443: bind: cannot assign requested address

only the nginx-web is down.

**Comment by evertramos** [comment]
@Guiraud 

Do not put your IP address here.... 

You have this port already being used by other services, please check it:

```bash
$ netstat -lt
```

or

´´´ bash
$ ss -lt
´´´

And check what services are running on port 443.

**Comment by evertramos** [comment]
it this is not the case... your IP address is wrong... you must check it:

```bash
$ ip address 
```


check your IP address for external access if it is in Amazon as an example you must your the internal which is binded to the external ip address.

**Comment by Guiraud** [comment]
Solved by using the internal Ip address of the vps instead of the external
