### ISSUE TITLE
TOS hash mismatch

### ISSUE THREAD

**Issue by bollerdominik** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#15]
I am trying to run the exact example shown here on my digitalocean ubuntu docker droplet.

What I changed in the .env is the filepath and IP.
Then I run ./run.sh
When I run the command to start my web app (httpd - like example) I of course changed my domain and email address.

After starting the new container I can see in the docker-compose logs following:

> nginx-letsencrypt    | 2017-11-15 13:03:38,628:INFO:simp_le:1213: Generating new account key
> nginx-letsencrypt    | TOS hash mismatch. Found: f33c27745f2bd87344be790465ef984a972fd539dc83bd4f61d4242c607ef1ee.¨

As a result the app works on http but not https

Please help

**Comment by wridgers** [comment]
[This](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277#issuecomment-344612875) is the answer you are looking for.

**Comment by evertramos** [comment]
@bollerdominik I didn´t had that problem before... I understand the issue, thanks to @wridgers and @buchdag we will keep it watching!

**Comment by bollerdominik** [comment]
Thanks guys. Feel free to close this

**Comment by evertramos** [comment]
@bollerdominik we will close when it solved, thanks for the issue.

But, please, did you manage to change the hash?

Just run your enviornment and before start the new container access your **nginx-letsencrypt** container and update the hash.

```
# docker exec -it nginx-letsencrypt bash
``` 

And in the container you do:
```
# vi letsencrypt_service
```

Update the line 6 with new has:

`cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b`

**Comment by bollerdominik** [comment]
I solved it by passing the hash to nginx-letsencrypt with 
` ACME_TOS_HASH: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b` 
in docker-compose.yml

Thank you

**Comment by Neol3108** [comment]
I changed my ACME_TOS_HASH but I'm still getting this error: https://pastebin.com/raw/7jDWLZCq
It seems my nginx-letsencrypt container is not able to contact Let's Encrypts servers over https? Does anyone know how to fix?

**Comment by evertramos** [comment]
@Neol3108 did you change anything in the `simp_le.py` besides what is mentioned here? You might try to rebuild you letsencrypt container as of:

```
git clone --branch tos-fix https://github.com/buchdag/docker-letsencrypt-nginx-proxy-companion.git
cd docker-letsencrypt-nginx-proxy-companion
docker build -t jrcs/letsencrypt-nginx-proxy-companion:latest .
```

As of https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277#issuecomment-344612875

**Comment by evertramos** [comment]
@bollerdominik 

It has been corrected on the origin as of https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277#issuecomment-344612875.

So we will close this issue. 

Thanks!

**Comment by Neol3108** [comment]
@evertramos I deleted the entire proxy and pulled everything again, also pulled the project from git again.
Now I get this error on nginx-letsencrypt: https://pastebin.com/raw/9xxmkNZp

**Comment by evertramos** [comment]
@Neol3108 that´s weiard... just start over and it ran. Which server provider you are using? Can you ping lets encrypt servers? It should be working now pretty well.

**Comment by buchdag** [comment]
@Neol3108 can you `curl https://acme-staging.api.letsencrypt.org/directory` from your host ?

**Comment by Neol3108** [comment]
@evertramos @buchdag I'm very new to Docker in general. But I think when I add a container to the network created when I ./run.sh It doesn't have internet access... I'm using UFW which I found out after I installed it doesnt work with Docker so well.. Do you know a solution? I'm able to access the proxy and the servers hooked up to it. Just not over https (because the cert cannot be created). The containers in the network just arent able to communicate with anything outside of the network.

**Comment by evertramos** [comment]
@Neol3108 UFW does not affect your docker environment... because when you start your doker service it create the rules before ufw on your iptables, so it should work just fine. I suggest you update your docker and restart the service and try it again. You should be able to get it working.

**Comment by rriemann** [comment]
I migrated today to this docker-compose file and got the error:

```
Creating/renewal my.public.domain certificates... (my.public.domain)
2017-11-26 21:49:33,184:INFO:simp_le:1213: Generating new account key
TOS hash mismatch. Found: cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b.
```

I appended to the image name ":latest" to make sure I have a recent version, but this did not have any effect.

**Comment by evertramos** [comment]
Hello @rriemann,

This should be working just fine, I restart my test environmnet and it just work. Please check if you can `curl https://acme-staging.api.letsencrypt.org/directory ` 

also try the following:

```
git clone https://github.com/buchdag/docker-letsencrypt-nginx-proxy-companion.git
cd docker-letsencrypt-nginx-proxy-companion
git checkout master
docker build -t jrcs/letsencrypt-nginx-proxy-companion:latest .
```
Please let us know if it worked.
