### ISSUE TITLE
Issues with nginx-web container crashing.

### ISSUE THREAD

**Issue by GijsVermarien** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#152]
# Error description:
I tried editing the client_max_upload_size for my Nextcloud instance. but now nginx-web will not start anymore and fail with error: 
```
2019/06/10 14:20:07 [emerg] 1#1: "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/nginx.conf:20
nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/nginx.conf:20
```
When I attempt to start using the start.sh script. I also tried removing all images and containers, but the problem persists on recreation.

# Steps to reproduce
I added client_max_upload_size to the nginx.conf in the configuration file of Nginx

# Expected result
I can upload files larger than 1MB via my nextcloud container

# Error result
```
2019/06/10 14:20:07 [emerg] 1#1: "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/nginx.conf:20
nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/nginx.conf:20
```

# Comments
The nextcloud instance is hosted by: https://github.com/evertramos/docker-nextcloud-letsencrypt

If you need any more info please tell me

**Comment by evertramos** [comment]
In the proxy this option is already here:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/conf.d/uploadsize.conf

Not sure where you added but seems you have two options in the configuration file, reason it will not start the nginx.
