### ISSUE TITLE
proxy_pass {{ trim $proto }} results in 502 Bad Gateway between containers

### ISSUE THREAD

**Issue by IAMtheIAM** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#155]
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/621798e92235b6eb75e0d34d3b6209dfee96ff7d/nginx.tmpl#L284

This line of code has a problem. the `proxy_pass {{ trim $proto }}://{{ trim $upstream_name }};` causes an issue. `{{ trim $proto }}` translates into `https` and this causes the 502 Bad Gateway  error. If I change it to `		proxy_pass http://{{ trim $upstream_name }};` then immediately my new container is found by nginx and loads correctly.

Why is this variable used here and how is it supposed to work using `https`? Because let's say my container runs on localhost:3000 - well there's nothing telling localhost to serve over https, so it fails. Please explain the logic here and I Will PR if needed

**Comment by evertramos** [comment]
This is something you must go to this repo:

https://github.com/jwilder/nginx-proxy

Did you run `start script` to update this file locally? If so... please post this issue in @jwilder repo.

Thanks!

**Comment by IAMtheIAM** [comment]
@evertramos Hi, thanks for the reply. Yes I did run the `start` script and it was auto downloading the new template (which was a big problem for me, because the template is broke). I will report this to them!
