### ISSUE TITLE
yacy

### ISSUE THREAD

**Issue by SnuppeDeluxe** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#156]
Your configuration is awesome.
I use it by my own and tell everybody, who want's to use nextcloud.

Is there a docker-compose for yacy, too?
I tried some configurations, but I#m to stupid for the right configuration.

**Comment by evertramos** [comment]
Hello @SnuppeDeluxe,

I don´t know yacy... please send me an email to contact@budhi.com.br I can check what I can do on that.

Cheers!
