### ISSUE TITLE
Vue rewrite

### ISSUE THREAD

**Issue by cwilby** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#162]
I'm having trouble running a Vue application that uses HTML5 routing.  It is running in a container that exposes port 80.  I'm using nginx-proxy to forward requests to that container.

The initial page load works, but if I browse to a URL, nginx-proxy returns a 404 before the request can be handled by the Vue container.

How can I ensure requests make it all the way to the Vue container via nginx-proxy?

---

On a separate note - this project is amazing!  Thanks to all contributors for their work.

**Comment by cwilby** [comment]
Found the issue - it was nothing to do with this project.  I was using `http-server` to serve requests in the Vue container. 

I've swapped it for `nginx` and all is working now 😊

**Comment by evertramos** [comment]
Thanks for you reply on https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/138 

Life is being crazy these days and no time at all for this project at the moment.

Cheers!
