### ISSUE TITLE
How to serve files directly from the nginx container

### ISSUE THREAD

**Issue by pieroit** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#165]
Sorry guys if I make a newb question.

Everything is working fine (using this project in combination with the wordpress one) and I thank you for this amazing tool.

I want to reserve a subdirectory of a domain for serving static files, directly from the nginx container. So I need somehow to override the proxy behaviour and just serve files from nginx instead of redirecting to the WP container.

I spent a couple of days editing a custom config file in `data/conf.d`, which has no effect at the moment. The config option in .env is on: `USE_NGINX_CONF_FILES=true`

Something like
```
server {
	listen 443 ssl http2 ;
	server_name <same_server_name_as_the_one_in_default.conf>;
	location /subdirectory {
		root /usr/share/nginx/html/;	
	}
}
```

I probably should study nginx better, but don't know if I'm doing something conceptually wrong or just missing a command in the syntax.

Or maybe I get this all wrong. Maybe I need a subdomain?
Please help :')

**Comment by evertramos** [comment]
The idea of having a proxy is to be able to build anything behind it, so you get a fresh nginx and configure as you wish to serve your files. 

This is how I would do it:

https://github.com/evertramos/nginx-behind-proxy

Hope it was of help!

**Comment by pieroit** [comment]
Took me a couple of days to understand, at the end I managed to make it work following your tip.
I've got a long way to go to understand what's going on under the hood. In the meanwhile, thank you so much :+1: 

Do you accept donations? Can't see the donate button

**Comment by evertramos** [comment]
Sure I do!!!

Pay pal > evert (dot) ramos (at) gmail (dot) com

Thanks and if you use another or any app let me know.

**Comment by evertramos** [comment]
I put a peerpay just in case! =)

**Comment by pieroit** [comment]
Paypal says you only accept donations on your website? I guess you need to activate some options. As for beerpay looks cool but I don't use stripe ;)
Let me know when I can try again

**Comment by evertramos** [comment]
paypal in Brazil has some strick rules for receiving money to avoid corruption... it must be sent as services.. as it seems... 

I need to set you as a contact and we could try again... 

if you could send me an email we try to set it up.

Thanks anyway!

**Comment by Alechan** [comment]
> https://github.com/evertramos/nginx-behind-proxy

I'm a little late, but would this mean having 2 nginx containers? And the one from the "sobfolder" would just be a proxy?
Wouldn't this "nested" nginx only forward HTTP requests to the container? If, for example, I'm running a container with a REST API documented with OpenAPI, then it would show that it only accepts HTTP because the nested web container was reached through http? Even though the "upper" nginx was reached through https?
