### ISSUE TITLE
Several WebApps on one Server

### ISSUE THREAD

**Issue by Cuthbert1337** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#166]
Hi, I'm really noob but I hope you'll point me into the right direction.

# Error description:
I successfully set up a Wordpress WebApp with your repositories and description. Everything works like a charm.
Now I wanted to add a Nextcloud instance on the same server/domain/IP. 

# Steps to reproduce
So I created another directory and downloaded your Nextcloud Docker Compose repo. I edited the .env accordingly the sample, especially:

VIRTUAL_HOST=same-host-as-wordpress/cloud
LETSENCRYPT_HOST=same-host-as-wordpress/cloud

# Expected result
Obviously My intention was to reach my Nextcloud instance via same-host-as-wordpress/cloud. 

# Error result
But also obviously that is not working. I think it's a lack of understanding here on my side.

# Comments
What is the correct way to implement a multi web app environment on one server via docker and with let's encrypt? Is virtual hosting possible, if yes how? 
If nothing else is it possible to use another port with letsencrypt certificate e.g. same-host-as-wordpress:8080

**Comment by pgassmann** [comment]
The way this is designed for is to use multiple domains. The IP can be the same.

Example:

wordpress:
```
VIRTUAL_HOST=www.your-domain.com,your-domain.com
LETSENCRYPT_HOST=www.your-domain.com,your-domain.com
```

nextcloud:
```
VIRTUAL_HOST=files.your-domain.com
LETSENCRYPT_HOST=files.your-domain.com
```

In your DNS you can use an A record
`files IN A <YOUR-SERVER-IP>`

 or a CNAME
`files IN CNAME www`

**Comment by Cuthbert1337** [comment]
Thanks for the CNAME advice. This did the trick for me.
Subdomain: cloud.domain.com
CNAME: domain.com
