### ISSUE TITLE
503 error on "www" domains or IP access

### ISSUE THREAD

**Issue by Darksoulsong** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#167]
# Error description:
I'm using [this](https://github.com/evertramos/docker-wordpress-letsencrypt) docker setup for Wordpress plus https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion on a VPS and everything worked as expected, except for domains that start with "www" or IP based.

# Steps to reproduce
- Clone the https://github.com/evertramos/docker-wordpress-letsencrypt repo and follow the instructions
- Clone the https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion and follow the README instructions
- Navigate to your domain (eg. "http(s)://xyz.com") [works!] 
- Navigate to your domain prefixing it with "www" or by direct inputting the IP (eg. "www.xyz.com" or "xxx.xxx.xxx.xxx""
 [fails]
# Expected result
- Navigation should occur for "http(s)://www.xyz.com" or "http(s)://xxx.xxx.xxx.xxx" successfully.

# Error result
Navigation to "http(s)://www.xyz.com" or "http(s)://xxx.xxx.xxx.xxx" is causing the server to throw the "503 Service Temporarily Unavailable" error.

# Comments
- Output of **docker logs nginx-web**:

https://pastebin.com/JN3r7z8n

**Comment by evertramos** [comment]
Hello @Darksoulsong,

First you must set up the proxy then the wordpress... and your issue is probably related to the VIRTUAL_HOST you set up in your wodpress .env file... did you put the 'www.' domain in your settings?

**Comment by Darksoulsong** [comment]
Hey @evertramos, thank you for your reply!
My .env file is below.

So, if I understood you correctly, I should add a "www.xyz.com" domain in to the "DOMAINS"section?

```
# .env file to set up your wordpress site

#
# Network name
# 
# Your container app must use a network conencted to your webproxy 
# https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
#
NETWORK=webproxy

#
# Database Container configuration
# We recommend MySQL or MariaDB - please update docker-compose file if needed.
#
CONTAINER_DB_NAME=db

# Path to store your database
DB_PATH=./db_data

# Root password for your database
MYSQL_ROOT_PASSWORD=somepwd

# Database name, user and password for your wordpress
MYSQL_DATABASE=xyz
MYSQL_USER=twlws
MYSQL_PASSWORD=somepwd

#
# Wordpress Container configuration
#
CONTAINER_WP_NAME=xyz

# Path to store your wordpress files
WP_CORE=./bkp/xyz.com
WP_CONTENT=./bkp/wp-content

# Table prefix
WORDPRESS_TABLE_PREFIX=xyz_

# Your domain (or domains)
DOMAINS=xyz.com

```

**Comment by evertramos** [comment]
yes sir!

just put all domains that must be validated by the ssl and you should be fine!

**Comment by Darksoulsong** [comment]
Awesome, it works. Thanks a lot!
