### ISSUE TITLE
Reboot docker host server cause 500 gateway error

### ISSUE THREAD

**Issue by sharethl** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#17]
# Error description:
Configured nginx, wordpress, but after rebooting server, cannot show the website again.
I tried restart all containers.
What should I do?

# Steps to reproduce
1. config nginx docker
2. config wordpress
3. wordpress works
4. restart server

# Expected result
after reboot, nginx should work again.

here is the log from nginx.
`
2017/11/19 18:56:26 [error] 7#7: *5 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.1.1, server: www.sectiongo.com, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.18.0.6:443/favicon.ico", host: "www.sectiongo.com", referrer: "https://www.sectiongo.com/"
www.sectiongo.com 192.168.1.1 - - [19/Nov/2017:18:56:26 +0000] "GET /favicon.ico HTTP/2.0" 502 575 "https://www.sectiongo.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
`

# Error result

# Comments

**Comment by sharethl** [comment]
Nvm, I found that nginx-gen also need to be started.

**Comment by evertramos** [comment]
Hello @sharethl,

Thanks for your reply. Are you using different `docker-compose.yml` for webproxy and wordpress?

You should NOT need to start the webproxy's containers, actually... Not sure what changed in moby recently, but "unless-stopped" should work fine. But YOU ARE RIGHT, it did not restarted the container. So, I have changed the `restart` option to `always`.

Thank you very much for you comment.
