### ISSUE TITLE
http ok, https times out (from internal network only)

### ISSUE THREAD

**Issue by fractalf** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#171]
Hi, first **thanks** for a great repo and all work put into it! My issue might be a bit on the edge and not related to this, so if it's way off, please just close.

Anyway, I've been running this setup for a couple of weeks now with great success. Today though I reinstalled the server (Ubuntu 19.04 before and after), re-did everything like the first time and now I cant access the sites on https from within the local network. The connection just times out.

Any tips/clues are most appreciated! :)

Some more details:

- The server is behind a router (NAT-ing ports etc is ok, not changed since it was working)
- Lets encrypt works fine.
- Everything works fine when accessing my server from *outside* the network ("The Internet")
- Only problem is when on the local network https times out, not even showing in the nginx-web logs

Thanks

**Comment by evertramos** [comment]
Hello @fractalf!

I believe your issue, as you said, has nothing to do with this proxy.... once the proxy does not sees it... you issue is the dns in the local network you are using it...  you must go over internet to access the website and validate the ssl certificate.... or you will need to set the local ip address as your domain in your hosts file. Please check the route your browser is doing when trying to access the sites on local network. Hope it was of help!

**Comment by fractalf** [comment]
Thanks for you reply @evertramos :)

I got it working by manually putting my sub-domain in `/etc/hosts`. Don't know why I didn't try that. Probably because it just worked out of the box the last time I set this up (without editing the hosts file)

Anyway, filing this under /dev/weird/stuff :)

**Comment by evertramos** [comment]
no specific reason about volumes... but feel free to use it, just make sure is persistent and backed up.

Cheers!

**Comment by fractalf** [comment]
Hahaha! This is kind of hilarious. Sometimes one just forget the most basic of all.

![image](https://user-images.githubusercontent.com/5707457/70746794-cfc55400-1d26-11ea-9a77-b177bfa3a413.png)
(from another forum with same problem)

Well, I did it and it worked. I think I spend like 2 workdays all in all debugging this :D
