### ISSUE TITLE
Failed to generate cert due to ACMEv1 account is dissabled

### ISSUE THREAD

**Issue by rickyzhang82** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#172]
# Error description:
One of the container failed with errors:
```
2019-10-11 01:34:20,059:INFO:simp_le:1382: Generating new account key
ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

# Steps to reproduce
`./start.sh`

# Expected result
Get cert.

# Error result
No cert.

# Comments
Errors come from `docker logs -f nginx-letsencrypt`

**Comment by evertramos** [comment]
Hello @rickyzhang82!

Did you start any other service? Did you set a domain to your ip address and ran the test_ssl script?

Please provide some more info... yesterday I got a new server running and it works like a charm!

**Comment by rickyzhang82** [comment]
It is related to the recent change from letsencrypt. They decided that any new account must go through ACMEv2. For old account, ACMEv1 is still accessible until some time next year. Right now I used a acme.sh script to grab it directly and do a reverse https proxy from Nginx on the host.

**Comment by evertramos** [comment]
so this is something you must post on [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) or [simp_le](https://github.com/zenhack/simp_le).

Thanks!
