### ISSUE TITLE
No "Local - Manage the local Docker environment" option

### ISSUE THREAD

**Issue by catalinroweb** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#175]
# Error description:
I've deployed Portainer and after going to my specified ip, i didn't have "Local" option, I only have 
- Agent
- Edge Agent
- Docker
- Azure

# Steps to reproduce
Deploy configuration, go to specified ip and make initial configs

# Expected result
See Local option besides Agent, Edge Agent, Docker and Azure

# Error result
No Local option

# Comments
I

**Comment by evertramos** [comment]
Sorry @catalinroweb... I didn´t understand your issue... this repo is for the proxy only. If you have issues with Portainer post it on the [docker-portainer-letsencrypt](https://github.com/evertramos/docker-portainer-letsencrypt) repo.

Thanks!
