### ISSUE TITLE
Question: Multiple virtual hosts and ports in the same container

### ISSUE THREAD

**Issue by ja573** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#183]
Is it at all possible to configure a single container to use two different domains, each mapped to a different port on the same container? E.g. api.test.com on port 9000 and test.com on port 8080

**Comment by evertramos** [comment]
Dude, I don´t think so... not through this proxy the way is designed.

**Comment by ja573** [comment]
Fair enough. After my comment I had a closer look at how it's all glued together and it seems like everything would need to be rethought to allow this feature

**Comment by coreyjewett** [comment]
"Multiple hosts can be separated using commas." -- https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Basic-usage.md#step-3---proxyed-containers

See also [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy#multiple-ports) regarding it's ability to specify ports. That's probably where you would want to open this issue to see if it is addressable.
