### ISSUE TITLE
proxy pass system service

### ISSUE THREAD

**Issue by GijsVermarien** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#197]
# Error description:
I wish to reverse proxy a system service that listens to *9090 on the system, I want it to also listen on domain.com:9090 on my main domain. How do I add this to the configuration before running `docker-compose up -d`?

**Comment by evertramos** [comment]
You should open the container port and access directly not through the proxy...

**Comment by evertramos** [comment]
Or you could try to set up a specific settings for nginx as of:

https://github.com/nginx-proxy/nginx-proxy#per-virtual_host
