### ISSUE TITLE
How to Change Nginx Port

### ISSUE THREAD

**Issue by Tofdu31** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#198]
Hi Evert,

By default, Nginx HTTP server listens for incoming connection and binds on port 80 and 443.

Is it possible to configure so that NGINX uses a specific port? Example: 3200
Is it also possible that the other projects (example Portainer) can have a certificate and operate on the port specified by NGNIX, example port: 3200

I open docker-compose.yml
` ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"` 

Can you validate this modification
` ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-4443}:4443"`

Thank you for your reply

Christophe

**Comment by Tofdu31** [comment]
Ooops I'm sorry. Just see the readme...
Using different ports to be proxied
If your service container runs on port 8545 you probably will need to add the VIRTUAL_PORT environment variable to your container, in the docker-compose.yml, as of:

parity
    image: parity/parity:v1.8.9
    [...]
    environment:
      [...]
      VIRTUAL_PORT: 8545
Or as of below:

docker run [...] -e VIRTUAL_PORT=8545 [...]

**Comment by Tofdu31** [comment]
Finally it's no ok, please help me ;)

**Comment by wordstospend** [comment]
A quick answer to part of your question:
`VIRTUAL_PORT` - disambiguates which port traffic should be forwarded to when your app container exposes more than one port

**Comment by Tofdu31** [comment]
Hi all,
In file  .env i change the value :
`DOCKER_HTTP=8580
DOCKER_HTTPS=8545`

When i start nginx (sudo ./start) I have an error : 
`ERROR: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (d44828534637495c1f17732c2ad4bd489eb7cda4cccfe6fa5b845022b0683f7c): Error starting userland proxy: listen tcp 82.64.68.35:8580: bind: cannot assign requested address
ERROR: Encountered errors while bringing up the project.`

Have you an idea ?

Thank for your help

Tof

**Comment by Tofdu31** [comment]
Arfff, It's  OK
I file .env, indicate your **INTERNAL** IP and not external IP when you are after a router in your house...
