### ISSUE TITLE
set label

### ISSUE THREAD

**Issue by rriemann** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#20]
I have errors but do not know if this is linked.

The description of the letsencrypt companion says:

> The "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen" label - set this label on the docker-gen container to tell the docker-letsencrypt-nginx-proxy-companion container to use it as the docker-gen when it's split from nginx (separate containers).

source: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#optional-container-environment-variables

We do not set this label. Should we better?

**Comment by evertramos** [comment]
Yes we do, if check our nginx container in https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/docker-compose.yml you can check that.
