### ISSUE TITLE
Can I use this for other hosts than sites hosted on the local docker?

### ISSUE THREAD

**Issue by fribse** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#201]
I love the dynamic setup this provides, one question though.
I have a need to have a website hosted on another server than the local docker (compose) setup.
Can I do this with this setup? And if so, how do I do that?
I guess I could make a container with a nginx and attach it to this with the proper variables, and let the 'client-nginx' forward the request out of the docker, but it seems like overkill, is there simpler way of doing this?

**Comment by evertramos** [comment]
Hello @fribse,

Never used this way... but would be easy and fast to use an nginx as simple as this one:

https://github.com/evertramos/nginx-behind-proxy

**Comment by fribse** [comment]
It is brilliantly simple. Thankyou, it seems to work fine!

**Comment by fribse** [comment]
Oh, while I wait on the developers container that will be on the inside of the firewall, I was just thinking, don't I need to allow the docker-compose access to the 'real' network for it to work? And if so, how do I do that?

**Comment by evertramos** [comment]
I don´t understand your question... your new server where you pointed should manage whatever it arrives to it. Don´t understand your environment so kind hard to solve what you need...

**Comment by fribse** [comment]
Sorry, I'm being unclear. The nginx you've suggested here, that will forward reqeusts to the external server, whatever that may be, is that allowed to use the normal 'host' network, and not just the internal docker network?

**Comment by evertramos** [comment]
it can you any network you set up in your compose file... but it must be on the proxy network for external access from the proxy container.

**Comment by fribse** [comment]
Ok, great, thankyou, I'll try it out further.
