### ISSUE TITLE
I have a question, how do I specify a container that "doesn't" go through this nginx

### ISSUE THREAD

**Issue by 99Kies** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#202]
# Error description:
I have a question, how do I specify a container that doesn't go through "this nginx

# Steps to reproduce

There are two services(Just one machine!), such as a.foo.com and b.foo.com. I just want a.foo.com to resolve to HTTPS and b.foo.com to HTTP by default.

# Expected result

# Error result

# Comments

**Comment by evertramos** [comment]
remove the LETSENCRYPT_HOST ON THE b.foo.com compose file and add it to the a.foo.com.
