### ISSUE TITLE
Certificate renewal fails automation

### ISSUE THREAD

**Issue by chenningg** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#204]
# Error description:
Received an email saying that certificates for certain domains were expiring in 19 days, when the certificates should have been renewed within 30 days of expiry.

# Steps to reproduce
Ran this image in a docker-compose configuration. Standard settings, used the default .env sample provided.

# Expected result
Certificates should auto renew within 30 days of expiry

# Error result
Log files attached:

> /etc/nginx/certs/commento.investingfortwo.com /app
> Creating/renewal commento.investingfortwo.com certificates... (commento.investingfortwo.com)
> 2020-05-01 15:56:45,692:INFO:simp_le:1545: Certificates already exist and renewal is not necessary, exiting with status code 1.
> /app
> /etc/nginx/certs/investingfortwo.com /app
> Creating/renewal investingfortwo.com certificates... (investingfortwo.com www.investingfortwo.com blog.investingfortwo.com)
> 2020-05-01 15:56:47,362:INFO:simp_le:1414: Generating new certificate private key
> 2020-05-01 15:56:50,810:ERROR:simp_le:1381: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v02.api.letsencrypt.org/acme/authz-v3/4298031001
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1370, in finalize_order
>     finalized_order = client.poll_and_finalize(order)
>   File "/usr/lib/python3.8/site-packages/acme/client.py", line 712, in poll_and_finalize
>     orderr = self.poll_authorizations(orderr, deadline)
>   File "/usr/lib/python3.8/site-packages/acme/client.py", line 736, in poll_authorizations
>     raise errors.ValidationError(failed)
> acme.errors.ValidationError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1443, in persist_new_data
>     order = finalize_order(client, order)
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1397, in finalize_order
>     raise Error('Challenge validation has failed, see error log.')
> simp_le.Error: Challenge validation has failed, see error log.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1565, in main
>     return main_with_exceptions(cli_args)
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1549, in main_with_exceptions
>     persist_new_data(args, existing_data)
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1459, in persist_new_data
>     persist_data(args, existing_data, new_data=IOPlugin.Data(
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 1128, in persist_data
>     plugin.save(new_data)
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 557, in save
>     key = self.dump_key(data.key)
>   File "/usr/lib/python3.8/site-packages/simp_le.py", line 455, in dump_key
>     return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
> AttributeError: 'NoneType' object has no attribute 'wrapped'
> 
> Unhandled error has happened, traceback is above
> 
> Debugging tips: -v improves output verbosity. Help is available under --help.
> /app
> Sleep for 3600s

# Comments
Sorry, quite new to this. I'm not sure how to make the automation work. From the error, it appears that blog.investingfortwo.com is invalid because it cannot be reached. I have removed the record from my DNS quite some time ago, and removed it from the docker-compose file as well. How do I go about deleting the certificates for regeneration?

Further information:
- My website is behind Cloudflare with Full(strict) SSL on. Does this affect things?
- I'm hosted on DigitalOcean, and have setup firewall on the DigitalOcean droplet (VPS) to only allow inbound traffic through Cloudflare IPs through both http and https ports. All outbound connections are allowed.
- I do not have any AAAA entries in the DNS, only A entries of my main domains to the server IP.

How do I set up auto renewal? In addition, as a quick fix measure, how do I manually regenerate the certificates? Can I simply delete everything in ./nginx-data/certs? If not, what files should I delete before I do docker-compose down and up again? Thank you.

**Comment by evertramos** [comment]
With CloudFlare you must disable proxy in order to generate and renew certificate... 

To disable the url you stop the container that has this url, remove the url from the domain list and start again.

**Comment by chenningg** [comment]
In that case automatic renewal will not work and I have to manually disable cloudflare, regenerate the certs every time right? In addition, what files can I delete in the certs folder should I wish to remove the old certificates?

**Comment by evertramos** [comment]
I wouldn´t remove the old certificates... the proxy will do it by itself. 

And yes you should disable proxy on CloudFlare everytime in order to renew certificates.

**Comment by chenningg** [comment]
Okay thank you! I will try to regenerate the certificates.

**Comment by meodemsao** [comment]
@chenningg how are u config with cloudflare, 
when i config with cloudflare proxied i can't make out website 
p/s sorry because comment on closed issues

**Comment by evertramos** [comment]
you can't... you must disable cloudflare proxy renew and start again the cloudflare proxy....

**Comment by meodemsao** [comment]
@evertramos i don't really understand you mean 
Can you explain for me

**Comment by meodemsao** [comment]
before i using with digital ocean server everything work well
when i using with aws ec2 + cloudflare it have many bug

**Comment by evertramos** [comment]
cloudflare is a proxy itself... if you want to use this repo.... when renewing certificates, you must disable the cloudflare proxy while renewing the letsencrypt certificates. got it?

**Comment by meodemsao** [comment]
@evertramos after that i can reopen proxied ?

**Comment by evertramos** [comment]
yes you can! only during renew process....

**Comment by chenningg** [comment]
Hi @meodemsao, it appears that for the FIRST time you generate a certificate, you will have to turn off cloudflare proxy so they can reach your website to verify the cert. If you already have an existing cert, then even if you keep cloudflare proxy on, you will be able to renew the cert since your website can be reached. My issue occurred because I had an erroneous domain in the cert request which couldn't be found, thus throwing an error into cert renewal.

**Comment by meodemsao** [comment]
@chenningg my issue is use public ip in .env file, when i using private ip (aws ec2 server) every thing work well
I don't need turn off proxied in Cloudflare if  setting Cloudflare SSL to option

```Full
Encrypts end-to-end, using a self signed certificate on the server ```
