### ISSUE TITLE
Is there a way to isolate container from internet?

### ISSUE THREAD

**Issue by nicolas-besnard** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#21]
Right now, every container can be accessed by internet. Wouldn't it be a good idea to let `docker-gen` and `letsencrypt` on a different network, and just the proxy to access internet?

I'm new to Docker, I might misunderstand something!

**Comment by evertramos** [comment]
Hello @nicolas-besnard,

The containers `Letsencrypt` and `docker-gen` are not accessible from the internet, even being on the same network. 

And it´s necessary to be on the same network once it must keep track of the containers ip address to communicate with each other.

It´s pretty safe once the only container that has the `docker.sock` mounted it´s `docker-gen`.

**Comment by evertramos** [comment]
@nicolas-besnard this is not an issue... please read carefully all the information in this repo and the docker-gen, letsencrypt-companion and you will have much more information to get acquaintance with.
