### ISSUE TITLE
What about starting other docker-compose files?

### ISSUE THREAD

**Issue by lonnietc** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#210]
Hello,

I am going to try and use your docker-compose script to setup the main nginx-proxy for my server and have read about how to start up docker containers from the CLI to work under the proxy.

I have another docker-compose yml running for some other services which currently publicly expose 3 different ports that I am going to put on subdomains.

What I need to do is to figure out how to have those docker services from within my other docker-compose file be recognized by your nginx-proxy.

Do I just need to add the:

-e VIRTUAL_HOST=your.domain.com
-e LETSENCRYPT_HOST=your.domain.com

to my other docker compose file?
Thanks in advance

**Comment by evertramos** [comment]
Hello @lonnietc,

You need to add lines below in your case:

```
VIRTUAL_PORT: 1234
VIRTUAL_HOST: sub.domain.com
LETSENCRYPT_HOST: sub.domain.com
LETSENCRYPT_EMAIL: mail@mail.com
```

When it does not have default port (80/3000 etc) you add the port to make sure the proxy will forward to specific port.

Hope you get it working.

**Comment by lonnietc** [comment]
Thanks again and I will test it out on my other docker-compose file.

Just a question here.  You mentioned to use VIRTUAL_PORT when ports (80/3000) are not being used already. I know what is running on my ports and can configure them but I not have anything running on port 3000. 

Is that just for an example, or is something in your scripts using that port?
Thanks again

**Comment by lonnietc** [comment]
been waiting for a little while and it is still showing up as not secure.

For the "your.domain.com", I used a "subdomain.myydomain.com" (of course I used the real subdomain for my case)

But still no secure connection.

**Comment by evertramos** [comment]
you can check logs of letsencrypt container

`docker logs -f --tail 50 nginx-letsencrypt`

the ports was just an example....

**Comment by lonnietc** [comment]
Thanks, I have been able to track down things almost have things working the way that I need, but this last question popped up.

In normally running my docker containers I use the port directive "-p 80:8080" or "-p 443:8443" (for example) then I now want to still port map from the proxy going though, say port 443 but over to port 8443 on my container.

In your previous example of using the declaration:

VIRTUAL_PORT: 1234

would your port "1234" correspond to my docker inside port "8443" as the Proxy is already handling the actual 443?

Also, I have some other ports mapped on in my docker-compose file like:

8000:8000
8001:8001
8443:8443
8444:8444

This is for a Kong gateway that I am setting up.

How do I tell the nginx-proxy that I need 8444 on the proxy to map to 8444 on my 

sub1.domain.com

which is normally accessed via 

sub1.domain.com:8444

I think that if I can get a feeling for how this is done, then your script is the perfect solution to what I need.

Thanks again

**Comment by lonnietc** [comment]
I solved the base case of port mapping 80:8080 and 443:8443 via VIRTUAL_PORT

Thanks for all of the help
