### ISSUE TITLE
Browser warning on certificates presented from proxy

### ISSUE THREAD

**Issue by yash-ks** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#214]
# Error description:

# Steps to reproduce
Forward domain to host
Create a website and expose it via proxy companion
Navigate to website

# Expected result
No certificate errors or scary warnings

# Error result
Safari and Chrome give errors about "your data in insecure" due to certificate being generic with "lets-encrypt-nginx-proxy-companion" as owner rather than valid domain owner and email.

# Comments
Clean and useful code. Fixing this will make it more useful.

**Comment by evertramos** [comment]
if your certificate was generated then you should not have any issue with any browser... can you sent an printscreen?
