### ISSUE TITLE
multiple domain with single public ip use case

### ISSUE THREAD

**Issue by sicenul** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#217]
# Case
Based on diagram on your README.md. My website1 is located on container inside Server1 serving for domain example.com, and My website2 located on container inside Server2 serving example.org. Is it possible using your docker companion to obtain certificate for both website using single public IP?

Something like this:

![image](https://user-images.githubusercontent.com/64000634/87552157-7e75ac80-c6db-11ea-9b2d-80a5dcb53c6b.png)

# Expected result
* We can access: https://www.example.com
* We can access: https://www.example.org

# Comments
What should I do? Please  enlighten me. Thanks.

**Comment by evertramos** [comment]
Hello @sicenul,

I think this is a little out of scope... once this script is supposed to run in a single server... but as you described if you have two servers, you must have two public ip addresses or have a load balance, am I right?

Two different websites, in two different servers... you can sync certificates from the `./certs` folder if you intend so.

I might didn´t understand your real context....

**Comment by sicenul** [comment]
Sorry for my bad english :)
* I thought that nginx will act as reverse proxy and forward to my two servers.
* So I only need one IP Public on that nginx.
* example.com DNS A Record will be pointed to that public IP.
* example.org DNS A Record also will be pointed to that same public IP.

By using something like this config, and put it inside nginx conf maybe?:
```
server {
    listen 80;
    server_name example.com;

    location / {
        proxy_pass http://192.168.11.2:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```
```
server {
    listen 80;
    server_name example.org;

    location / {
        proxy_pass http://192.168.12.2:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Is that make sense to you? :sweat_smile: 
Or if this is not the right case for your docker script, then feel free to close this :slightly_smiling_face:

**Comment by evertramos** [comment]
Dude!

This proxy does the exaxt same thing you are trying to achieve. This is a reverse proxy, and it will do automatically what you are looking for, but all in one server, on public ip address.

> I wouldn´t mess up with the nginx files (proxy manages that) neither internal ip address (docker manages that part for you). 

Give it a try, fire this proxy and when it is running, start two container as a test:

Container 1
```bash
docker run -d -e VIRTUAL_HOST=example.com -e LETSENCRYPT_HOST=example.com -e LETSENCRYPT_EMAIL=your.email@your.domain.com --network=webproxy --name my_app httpd:alpine
```

Container 2
```bash
docker run -d -e VIRTUAL_HOST=example.org-e LETSENCRYPT_HOST=example.org -e LETSENCRYPT_EMAIL=your.email@your.domain.com --network=webproxy --name my_app httpd:alpine
```

**Comment by sicenul** [comment]
Thank you, but looks like both container should connect to the same network as proxy right? no matter where we put the container.
* If I put both container on the same server then there's no issue. Your configuration should just work. 
* But if I put both container on another server, then I have to find out how to connect the container with proxy, right?

**Comment by evertramos** [comment]
As I mentioned this should run in the same server. To run in multiple servers you could use a netowork relay which is not easy to set... or try Docker swarm, kubernete or even Traefik for that. All of them I have tested and works like a charm. Harder to set things up and some of them like kubernetes will demand at least three servers (one master and two slaves) to work in production and do its job! Otherwise... if you can use only one server this would attend.

Other option I have used to forward to external services were putting up a nginx container inside server proxy to forward connections to wherever I desire, I have a repo that shows that in an easy way..


https://github.com/evertramos/nginx-behind-proxy

**Comment by sicenul** [comment]
Thank you for your valuable time in responding my question @evertramos .
Since this is already out of scope, I'll close this issue. Again, thanks a bunch.

**Comment by evertramos** [comment]
Welcome! Let me know when you solve your issue!
