### ISSUE TITLE
FastCGI sent in stderr: Primary script unknown

### ISSUE THREAD

**Issue by babeuloula** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#219]
# Error description:

FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.6, server: , request: "HEAD / HTTP/1.1", upstream: "fastcgi://172.18.0.9:9000", host: "www.xxx.fr", referrer: "https://www.xxx.fr/

# Steps to reproduce

1. Clone and start this repo
1. Start a nginx & php-fpm container
1. Start e second nginx & php-fpm container

Randomly I've got this error and a 404 on both websites.

# Comments

My first website works with Slim Framework 3 and second with Symfony 5.1.

My nginx config: 

```
server_tokens off;

map $http_x_request_id $request_uid {
    default $http_x_request_id;
    "" $request_id;
}

log_format docker '$remote_addr - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time "$http_x_forwarded_for" $request_uid';

server {
    root /var/www/html/public;

    access_log /var/log/nginx/access.log docker;
    error_log /var/log/nginx/error.log error;

    add_header X-Request-Id $request_uid;

    client_max_body_size 20M;

    location / {
        try_files $uri /index.php$is_args$args;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }

    location ~ ^/index.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param HTTP_X_REQUEST_ID $request_uid;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
```

If you need more information tell me.

Thanks

**Comment by babeuloula** [comment]
My bad, it's a conflict with my nginx conf and php-fpm. I used the same service name for php-fpm in my both docker-compose and nginx conf on both websites.
And when nginx tried to connect to php, he tried with php:9000 but he found two service on the same network. 

So I've used an alias for my network and I've changed my nginx conf.

**Comment by cod3rshotout** [comment]
@babeuloula hi! maybe you could help me on this: https://github.com/evertramos/nginx-proxy-automation/issues/262

**Comment by evertramos** [comment]
Here is a working example:

[php-fpm](https://github.com/evertramos/nginx-proxy-automation/issues/262#issuecomment-812901849)
