### ISSUE TITLE
Update failed： 504 Gateway Time-out 504 Gateway Time-out nginx/1.19.1 

### ISSUE THREAD

**Issue by ACChe** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#220]
# Error description:
Update failed： 504 Gateway Time-out 504 Gateway Time-out nginx/1.19.1 

# Steps to reproduce
While I am installing or updating the plug-in, it will be always failed.

# Expected result
Plug-in installation or update successful.

# Error result
Update failed： 504 Gateway Time-out 504 Gateway Time-out nginx/1.19.1 

# Comments

How to fix the problem?

**Comment by evertramos** [comment]
This repo has no plugin.. does it? and if you are talking about the workpress.. it might has nothing to do with the proxy. Please open this issu in the wordpress repo.

**Comment by maltokyo** [comment]
Hi @evertramos - I know this is old, but I have a similar issue.  In my case, I have a site that sometimes takes a minute to respond when it is under heavy load.  And I would like Nginx to wait longer for it to load without returning 504.  How can I increase the timeout (time that Nginx will wait for the backend site)?

**Comment by evertramos** [comment]
Hello @maltokyo you can add any nginx general settings to this path https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/tree/master/conf.d and algo set the any default proxy setting and site settings, please check:

- https://github.com/nginx-proxy/nginx-proxy#custom-nginx-configuration
- https://github.com/nginx-proxy/nginx-proxy#per-virtual_host

**Comment by maltokyo** [comment]
Thanks!!
