### ISSUE TITLE
[Question] How to add a header for a single virtualhost?

### ISSUE THREAD

**Issue by mcastillof** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#242]
When you deploy your web containers, 'server' blocks are added to $NGINX_FILES_PATH/conf.d/default.conf.

I need to add a header to a single virtual host. How can I do this? 
This $NGINX_FILES_PATH/conf.d/default.conf file is autogenerated so I'm not going to edit it. (Should I?)

How to do this?

**Comment by evertramos** [comment]
Hello @mcastillof,

Don't messa up with your default file, please check that:

https://github.com/nginx-proxy/nginx-proxy#custom-nginx-configuration
