### ISSUE TITLE
Question about resolving web addresses between local web containers

### ISSUE THREAD

**Issue by ardiewen** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#245]
Hi there, I'm hoping you can provide some insights as to why this isn't working for me.

I have this repo running, and 2x web containers that have a nginx web server on port 80, and wordpress-php-fpm on 9000.

 For all intents and purposes, consider these web containers a slight adaptation of your [docker-wordpress](https://github.com/evertramos/docker-wordpress) setup.

My project structure looks like this:
```
|- webproxy
|   -- this repo
|- sub1.domain.com
|   -- nginx on 80
|   -- wordpress-php-fpm on 9000
|- sub2.domain.com
|   -- nginx on 80
|   -- wordpress-php-fpm on 9000
```

Everything works wonderfully, until I try to run some PHP scripts that reference the other subdomain, such as a database sync / migration plugin on wordpress.

For example, a PHP script on sub2.domain.com might want to curl https://sub1.domain.com... but it cannot resolve the address (Operation timed out).

If the PHP script attempts to curl any outside address, e.g. https://google.com, it resolves perfectly fine.

I tried curling from the nginx containers in the web containers as well, with the same result, so I don't think it's because the wordpress container is behind another nginx proxy.

Any idea why this doesn't work? Thanks in advance.

**Comment by evertramos** [comment]
I have seen this before... the work around would be to use the container name for internal purpose in the same docker network, but this wouldn't solve the issue.

**Comment by ardiewen** [comment]
@evertramos FYI - i fixed the cause of this.

For anyone that runs into this in the future, the problem in my case is the docker host had a firewall such as `ufw` active.

The problem was ufw is configured to accept lan requests, but the docker services were running on a different subnet. Turning ufw off, or creating an exception rule can solve this issue.
