### ISSUE TITLE
Why nginx.tmpl ?

### ISSUE THREAD

**Issue by rgarrigue** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#25]
Hello

I'ld like to know why you went all the way to make your own version of nginx template ? I'm working on using latest nginx + jwilder dockergen  + jrcs letsencrypt on a docker swarm, and that might be a very important point for me :-)

Cheers,

**Comment by evertramos** [comment]
Well I did not! Actually if you run my start.sh script it download the latest version from jwilder! =)

**Comment by evertramos** [comment]
Accidentally I found this (https://github.com/nextcloud/docker/issues/194) and I just publish NextCloud for this webproxy, which might be helpful:

https://github.com/evertramos/docker-nextcloud-letsencrypt

Cheers!

**Comment by rgarrigue** [comment]
Well, your full stack won't work in my use case. Jwilder's dockergen doesn't work in a docker swarm :-(
