### ISSUE TITLE
Gitlab SSL error:02001002

### ISSUE THREAD

**Issue by mikeevstropov** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#29]
To solve an error
```console
gitlab_1  | ==> /var/log/gitlab/nginx/error.log <==
gitlab_1  | 2017/12/30 16:23:16 [emerg] 3606#0: BIO_new_file("/etc/gitlab/ssl/gitlab.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/gitlab/ssl/gitlab.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
add following options into `GITLAB_OMNIBUS_CONFIG`
```
nginx['listen_port'] = 80
nginx['listen_https'] = false
nginx['proxy_set_headers'] = {
    "X-Forwarded-Proto" => "https",
    "X-Forwarded-Ssl" => "on"
}
```
[reference](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#supporting-proxied-ssl)

**Comment by evertramos** [comment]
What was the error in first place?

**Comment by mikeevstropov** [comment]
@evertramos You can use lable to mark issue as "external" instead of showing your displeasure. Thank you.

**Comment by evertramos** [comment]
@mikeevstropov sorry if you misunderstand me.... I just mark as **confusing** (I was confused) not _displeasure_... any way, that´s why I asked what was the error... quiet did not understand yet... but ok. Sorry anyway, did not mean any harm. Happy New Year!
