### ISSUE TITLE
Did this test on Ubuntu? I can't transfer to port 443 on my server.

### ISSUE THREAD

**Issue by onlyfly34** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#3]
I cloned this project. Try and debug to set up everthing.
But 443 port transmission doesn't work.
I use the command: 
`docker logs nginx`
And the response is:
`2017/08/21 09:26:52 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xxx.xx.xx, server: xxx.xx, request: "GET / HTTP/1.1", upstream: "https://172.18.0.6:443/", host: "xxx.xx"`

Is there any solution?

**Comment by evertramos** [comment]
It seems that you are using local net work `https://172.18.0.6:443/` which you probable changed the settings:

```
[...]
   ports:
      - 172.18.0.6:443:443
```

You must keep it only `443:443` in order to get your external ip address, and it will work.

**Comment by evertramos** [comment]
As of not geting any more replies... I will close this issue.
