### ISSUE TITLE
[Question] How to configure cleanly the default.conf file ? 

### ISSUE THREAD

**Issue by kevincaradant** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#30]
Hi @evertramos, 

Sorry if it a simple question but I read many times your README and try to find a solution via the previous questions asked by other users. I'm still sticked.

My computer is my own server. So I bought a domain name ( in this example, it's 'toto.com')  on OVH and I just configured the DynHost like that: storage.toto.com = MYEXTERNALIP.
So when you ask the `-e VIRTUAL_HOST=your.domain.com` or `-e LETSENCRYPT_HOST=your.domain.com` to start the docker container, I wrote something like this: 
```
docker run -d -e VIRTUAL_HOST=storage.toto.com \
              -e LETSENCRYPT_HOST=storage.toto.com \
              -e LETSENCRYPT_EMAIL=joe@toto.com \
              --network=webproxy \
              --name my_app \
              httpd:alpine
```
Are you agree with that ? 

BTW: When do I change `--network=webproxy` ? I didn't undertand this line ... In my case, I have only one virtual_host. Maybe later,  I will have more one VIRTUAL_HOST. So should I change something in this case ? 

Then: 

I need to have this configuration in default.conf file:

```
server {
  listen 4430;
  access_log /var/nginxSSL.txt;
  root /storage/myuser;
  autoindex on;
  ssl on;
  ssl_certificate .....;
  ssl_certificate_key ......;
  location / {
    try_files $uri $uri/ =404;
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/.htpasswd
  }
}
```
Before your docker, I wrote and defined fully the default.conf file by hand. 
After to follow your instructions, I remarks that in the default.conf file, these lines are missing:

> autoindex on;
> ssl on;
> root /storage/myuser; // this line is the most important for me 

Where can I define the `root` line. I have to mount a volume from the host I guess otherwise I can't have my files ? I saw a default.conf file in the data folder. Should I edit it directly ? 

Thank you in advance and sorry to be so confusing about all your stuff (BTW amazing) but which is new for me :)

Regards

**Comment by evertramos** [comment]
Hello @kevincaradant!

There is nothing basic on that!

About the network, the only thing you must have it´s your webproxy in the same network of your app container.

Regarding your future container, you can have **n** containers with that proxy.

And your storage... here is a few comments:

1. The proxy only validate your ssl and forward your request to your container. 

2. Your storage container must have your own nginx configure to run your app or in that case your Apache `httpd:alpine`.

3. The volume should not be mounted by your proxy.

Here is docker-compose file as example:

https://github.com/evertramos/docker-nextcloud-letsencrypt

Please let me know if you find your way out.

**Comment by kevincaradant** [comment]
Hi

I'm not sure to understand yet the step 2.
`Your storage container must have your own nginx configure to run your app or in that case your Apache httpd:alpine.`
 And the step 3.

**Comment by evertramos** [comment]
Hello @kevincaradant!

Well, sorry for my bad explanation....

You must have your webproxy running in first place, which you probably have. After that you will start a new container running your app.

**In this new container**, which you have your App running, you will configure whatever you must. If you use Apache, you set up your apache, if you use NGINX you set up your NGINX.

The proxy should be abstracted from your app.

All configuration, regarding your volumes should be set in your Containers App.

You do not need a third container as far as I understood.

Trying to make myself a little be more clear, what I do is, if I have a service that runs stand alone using docker, I just add the options to my App Container:

```
              -e VIRTUAL_HOST=storage.toto.com \
              -e LETSENCRYPT_HOST=storage.toto.com \
              -e LETSENCRYPT_EMAIL=joe@toto.com \
              --network=webproxy \
```

Please let me know if it was clear enough.

And this is my way of thinking which might not be the best, right or wrong... just my way of doing things.

Cheers!

**Comment by kevincaradant** [comment]
Hi

Thank you to try to explain again for me :D 

I didn't realized something, but the httpd:alpine is a my container with my own config !  So your first answer was clear. I thought, don't ask me why, "the famous proxy" was the https:alpine. But not at all.

So if I understood, in the container where you said ->
-e VIRTUAL_HOST=storage.toto.com \
              -e LETSENCRYPT_HOST=storage.toto.com \
              -e LETSENCRYPT_EMAIL=joe@toto.com \
              --network=webproxy \

In fact, I have to edit my nginx conf inside the nginx:alpine or apache with httpd:alpine and just add the env variables as you mentioned (virtual_host, letsencryp host and email)  and the proxy will do the stuff. 
Alright, I will try this week-end and come back to say you. That seems easy in my head now :)

**Comment by evertramos** [comment]
I will close but will wait your answer!

**Comment by kevincaradant** [comment]
Hey!

I think I miss something yet :/

This is my steps:

Step 1: I executed the command `./start.sh`

Step 2: I configured my ovh services with the domain name to be redirected to my external ip

Step 3: I created my nginx file under /home/kevin/nginx/nginx.conf:
```
events {
  worker_connections  4096;  ## Default: 1024
}

http {
  server {
    listen 80;
    access_log /var/nginxSSL.txt;
    root /kevin;
    autoindex on;
    location / {
      try_files $uri $uri/ =404;
    }
  }
}
```

Step 4: I started my own container (nginx) like that:

```
docker run -d -e VIRTUAL_HOST=storage.toto.com \
              -e LETSENCRYPT_HOST=storage.toto.com \
              -e LETSENCRYPT_EMAIL=toto@gmail.com \
              -v /home/kevin/nginx/nginx.conf:/etc/nginx/nginx.conf:ro \
              -v /home/kevin/nginx:/kevin \
              --network=webproxy \
              --name my_app \
              nginx:alpine

And finally, 
```

Step 5:
I opened Firefox, and I can access ONLY under http://storage.toto.com. Why I can't use the https with letsencrypt ? 

Thank you in advance @evertramos

**Comment by evertramos** [comment]
Hello @kevincaradant!!!

Well it seems everything is quiet right! Let´s see...

1. Did you letsencrypt container generate the certificates? I should be in `./data/certs/` folder. Please check that.

2. If you have the certificates running check your `./data/conf.d/default.conf` if you see the SSL configuration.

If the proxy is receiving ssl connections you will see some codes like these:

```
server {
        server_name budhi.com.br;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/budhi.com.br.crt;
        ssl_certificate_key /etc/nginx/certs/budhi.com.br.key;
        ssl_dhparam /etc/nginx/certs/budhi.com.br.dhparam.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://budhi.com.br;
        }
}
```

If it did not work, please post here you letsencrypt logs.

**Comment by kevincaradant** [comment]
1) OK

2) As I said in the edited message, I didn't have this snippet of code :)

3) Indeed, I getReloading nginx docker-gen (using separate container nginx-gen)...
```
Reloading nginx (using separate container nginx-web)...
Creating/renewal storage.caradantkevin.fr certificates... (storage.toto.com)
2018-01-08 23:48:04,131:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
2018-01-08 23:48:07,622:INFO:simp_le:1356: Generating new account key
2018-01-08 23:48:15,537:INFO:simp_le:1455: Generating new certificate private key
2018-01-08 23:48:25,783:ERROR:simp_le:1421: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/cynSEVKweQrly7XAwbm44eghBG4HgP5zquALsoHUK
2018-01-08 23:48:25,786:INFO:simp_le:463: Saving account_key.json
Challenge validation has failed, see error log.

Debugging tips: -v improves output verbosity. Help is available under --help.
 an error in the container docker.
```
I just realized that I'm using a 4G connexion for the moment. (my phone shared one connexion). I will retry with a real internet box because maybe there is a lot chance that my problem comes from that. 
I will edit this message in a few days :)

**Comment by evertramos** [comment]
@kevincaradant to make your letsencrypt generate your certificates and access it through https you must have you domain name settled to your ip address (storage.toto.com => your server ip address).

If you are using a 4G connection, you will probably get your ip address but it probably changes in a very short time.

**Comment by kevincaradant** [comment]
@evertramos, mhh no it's working with the external IP because I can access with http://storage.toto.com ;)

It's weird no ?

**Comment by evertramos** [comment]
Right, if you can access on http dns is correct.

Please tell me if you start webproxy using our script `start.sh`...

**Comment by kevincaradant** [comment]
I don't know why but with a real internet box (adsl / fiber) everything works well :D 
So I will wait to have internet at home. 4G is good to have internet but with docker, server etc it's not simple . Big thank you for your advice ! @evertramos 

BTW: some issues interesting on your repo seems to be written in spanish or italian, you should write in english only because people like me even using google trad, don't understand anything haha

**Comment by evertramos** [comment]
It´s written in Portuguese! I am from Brazil, and I will revise the text... sorry fot that!

And please, just tell me if you start the webproxy using our start script, because I have done some tests here, and there is a few times, for some version issues, the certificates could not be issued.

If you update your repo `git pull` and run our `start.sh` it should update everything for you and I truly believe it will work!

**Comment by kevincaradant** [comment]
haha Google trad didn't see that you wrote in Portuguese :D  

I will try as soon as possible but you will have to wait few days because it's seems with Docker ( and during the mount of volume ), I totally broken my home partition, everything was chown as root !, so Docker and a lot of things are broken ....
I need to format and install again all my Linux partition ;)

**Comment by Naramsim** [comment]
Hi @evertramos, basically I have developed my application which includes an Nginx container. Should I put my Nginx container behind your Nginx container?

**Comment by evertramos** [comment]
@Naramsim Yes Sir!

That's it! 

Don't forget to add the following environment options to your container:
```
[...]
              -e VIRTUAL_HOST=storage.toto.com \
              -e LETSENCRYPT_HOST=storage.toto.com \
              -e LETSENCRYPT_EMAIL=toto@gmail.com \
              --network=webproxy \
[...]
```

Any issue let us know.

**Comment by Naramsim** [comment]
@evertramos  Yes of course :)

But, will your Nginx container forward all the headers that my Nginx container will set? And vice-versa?

What is the purpose of vhost.d folder?

**Comment by evertramos** [comment]
@Naramsim the webproxy will forward the request to your container.

The `conf.d` folder should only be used if you want some specific configuration to your nginx proxy, such as  forward the real ip address instead of docker container ip address to your nginx, or the upload file size supported by the proxy etc.

I suggest you make a test to see if there is any further configuration you will need to set in proxy before going to add `conf.d` options. It might not be necessary.

**Comment by Naramsim** [comment]
Ok, thanks, basically I need a second Nginx container (to put behind yours) if I want to pass the traffic to a Node container and disable the cache for a service-worker.js file. Ok, perfect, thanks

**Comment by evertramos** [comment]
I will test that and add to conf.d option! Thanks!

**Comment by kevincaradant** [comment]
Hi @evertramos 

I come back because I again a little bit lost :P 

I had the port 443 already used :/, any idea how to do to avoid this error ? Which config should I change ?
```
Creating nginx-letsencrypt ... 

Creating nginx-letsencrypt ... done
int nginx-web (92896938ccba52d202d7e562fbda2ef8d162c90a51ebdb41e81e60502d66201c): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (92896938ccba52d202d7e562fbda2ef8d162c90a51ebdb41e81e60502d66201c): Bind for 0.0.0.0:443 failed: port is already allocated
```

Thank you :)

**Comment by evertramos** [comment]
You can not have two services running on the same port.

If you want to keep your current services on port 443 and start the webproxy on port 80 only, you must comment this line:

```bash
  ports:
      - "${IP:-0.0.0.0}:80:80"
#      - "${IP:-0.0.0.0}:443:443" # This line should be commented.
```

It should be commented on both files:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/docker-compose.yml
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/docker-compose-multiple-networks.yml

**Comment by kevincaradant** [comment]
Thanks I understand your answer but I thought to use https://myapp.com:4430? With the green lock thanks to your container let's encrypt. Is it possible? :)

**Comment by evertramos** [comment]
I think it could work as you mentioned using:

`yourdomain.com:4430`

But not sure if you will be able to generate let's encrypt that way... You could generate certificate and use it for sure, but never tested changing the ssl port.

I would suggest you to try and please let us know if it work and how id manage it to get it done.

Thanks

**Comment by kevincaradant** [comment]
Hi @evertramos 

I'm currently trying that but I'm wondering about this file: nginx.tmpl

I can see some extract of code where it's wrote: listen 443 and not 4430. 

This file is use to listen the host machine or inside the docker ? Because when I wrote this: 
${IP:-0.0.0.0}:4430:443

I don't know if nginx.tmpl should be edited or not for the 4430 value ....

Thank you

**Comment by evertramos** [comment]
@kevincaradant 

I would recommend to do not edit the `nginx.tmpl` file... this is made by the creator of the nginx-proxy, and always update with the latest version when you run start.

I would recommend once again to test it, have you tested yet? What was the results?

**Comment by kevincaradant** [comment]
Yep this is the log with docker-compose logs:

```
nginx-letsencrypt    | Sleep for 3600s
nginx-gen            | 2018/03/08 17:39:07 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | 2018/03/08 17:39:07 Generated '/app/letsencrypt_service_data' from 11 containers
nginx-gen            | 2018/03/08 17:39:07 Watching docker events
nginx-letsencrypt    | 2018/03/08 17:39:07 Running '/app/update_certs'
nginx-gen            | 2018/03/08 17:39:07 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | 2018/03/08 17:39:07 Watching docker events
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | 2018/03/08 17:39:07 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
``` 

I think something is missing because I got nly few logs

And in: /home/yourrepo/nginx/data/conf.d/default.conf
I have only the listen 80 without the snippet code with listen 443 or listen 4430 . SO I think something wrong. If you have any idea how to solve this. Or a way to get others logs :)

Thank you

**Comment by evertramos** [comment]
it´s not wrong... it´s correct.

As I mentioned in a previous message, the lets encrypt will not work.... that way because it´s suppose to listen on port 443, so you must get a working certificate and post inside the `/home/yourrepo/nginx/data/certs/yourdomain.com` to test it on.

After you having that the script will load the nginx port fowarding I belive.

**Comment by evertramos** [comment]
An if that does not work... you can generate your certificates, bind to the container you have, make your services work  with this certificate and get the proxy to forward from port 4430 to 443 in your container, which will have your service working correctly.

**Comment by kevincaradant** [comment]
ok I will try that you say and to be clear, normally, this should be working just in http isn't it ? For the moment it's not the case. 
443 is it the only problem ? 
I would reach to work at least http and https without certificate with 4430 but it's not the case, so ... I don't know :)

**Comment by kevincaradant** [comment]
I tried with the 443 and it's the same problem.
```
 CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If you haven't setup correct CAA fields or if your DNS provider does not support CAA, validation attempts after september 8, 2017 will fail.  Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/siCu1m93RUISSJBfa3cB4iI5H8dqPZYKwPK6Mrm
```

**Comment by kevincaradant** [comment]
@evertramos, I failed the edited message yesterday but the problem of reboot is for you :P 
I need to restart each time the three containers... without understand why ;)

**Comment by kevincaradant** [comment]
Hi
Really sorry to ask you to have your point of view about that but today, I don't know why but nothing happend anymore at https://myurl:4430 and I didn't touch anything :/
I tried since two hours to get something working but nothing ...
Maybe my previous problem is linked but I'm not sure ...

Did you see something wrong, it's all I have as logs and containers. A port can be missing ?:
![image](https://user-images.githubusercontent.com/6093175/37257018-93ca01e2-2563-11e8-8291-afc9356ce2be.png)

Logs:
```
nginx-letsencrypt    | Sleep for 3600s
nginx-gen            | 2018/03/11 18:31:04 Received event die for container eb8d62dbb4dc
nginx-letsencrypt    | 2018/03/11 18:29:26 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
nginx-gen            | 2018/03/11 18:31:04 Received event stop for container eb8d62dbb4dc
nginx-letsencrypt    | 2018/03/11 18:29:50 Received event start for container eb8d62dbb4dc
nginx-letsencrypt    | 2018/03/11 18:30:05 Debounce minTimer fired
nginx-gen            | 2018/03/11 18:31:07 Received event start for container eb8d62dbb4dc
nginx-letsencrypt    | 2018/03/11 18:30:05 Generated '/app/letsencrypt_service_data' from 13 containers
nginx-gen            | 2018/03/11 18:31:12 Debounce minTimer fired
nginx-letsencrypt    | 2018/03/11 18:30:05 Running '/app/update_certs'
nginx-gen            | 2018/03/11 18:31:12 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | /etc/nginx/certs/(toto.toto1.com) /app
nginx-gen            | 2018/03/11 18:31:31 Received signal: terminated
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container nginx-gen)...
nginx-letsencrypt    | Reloading nginx (using separate container nginx-web)...
nginx-letsencrypt    | Creating/renewal (toto.toto1.com) certificates... (toto.toto1.com)
nginx-gen            | 2018/03/11 18:31:31 Received signal: terminated
nginx-letsencrypt    | 2018-03-11 18:30:05,853:INFO:simp_le:1534: Certificates already exist and renewal is not necessary, exiting with status code 1.
nginx-gen            | 2018/03/11 18:34:23 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
nginx-letsencrypt    | /app
nginx-gen            | 2018/03/11 18:34:23 Watching docker events
nginx-letsencrypt    | Sleep for 3600s
```

**Comment by evertramos** [comment]
@kevincaradant 

it was working and just stop working? You must check logs and see what's wrong...  and once again, why you really need the have 443 running locally and not 80 in this server? Could you not set the 443 services into a container as well?

Are you using a local url? (https://myurl:4430/)

**Comment by kevincaradant** [comment]
For the logs, I have nothing so I don't understand. I restart 50 times the docker-compos so I was sticked.

When you said:
why you really need the have 443 running locally and not 80 in this server? 

I'm using a container docker-compose with 443 for my openvpn and need to keep it :).
Is you suggest me to run a container with 80? Which container with port 80? Because for my openvpn I need to keep the 443 port.

And yes I would like use https://toto.com:4430 but for the moment it's working only few times ')

**Comment by evertramos** [comment]
I would suggest you to put your vpn behind the proxy....
