### ISSUE TITLE
AH00558: httpd: Could not reliably determine the server's fully qualified domain name

### ISSUE THREAD

**Issue by kevincaradant** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#31]
Hi @evertramos 

I have an other problem I think with httpd.

```
docker run -d -e VIRTUAL_HOST=storage.toto.com \
              -e LETSENCRYPT_HOST=storage.toto.com \
              -e LETSENCRYPT_EMAIL=your.email@your.domain.com \
              --network=webproxy \
              --name my_app \
              httpd:alpine
```

Give me this error in the docker container:

```
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
```

Is it normal ? How to fix it in the case where it's not normal ? 
NB: Everything seems to work properly even with this error

**Comment by evertramos** [comment]
@kevincaradant this is your apache configuration in your container. I think It´s not a big deal, but if you want to remove that warning just add your own server name to Apache configuration or localhost as of:

https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers-fully-qualified-domain-n

Happy New Year!

**Comment by kevincaradant** [comment]
OK thank you I'm going to check that! Happy new year :D
