### ISSUE TITLE
[Question] How to expose multiple containers

### ISSUE THREAD

**Issue by haipham23** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#33]
At first I would like to apologize for my poor understanding of how nginx works.

Suppose I have 3 containers that need to expose to the public. And my domain name is `haipham.me`. All containers expose different ports to the host.

The first container (port 8080) should be accessible through haipham.me
The second container (port 8081) should be accessible through haipham.me/second
The third container (port 8082) should be accessible through haipham.me/third

Can I achieve the expected result above using this command?

```
docker run -d -e VIRTUAL_HOST=www.haipham.me \
              -e LETSENCRYPT_HOST=www.haipham.me \
              -e LETSENCRYPT_EMAIL=haipham23@gmail.com \
              --network=webproxy \
              --name first_container \
              first_container
```

**Comment by evertramos** [comment]
Hello @haipham23!

Let's see if I understand.... you want to type in your browser: haipham.me and access first conatiner, which only has port 8080 open? Is that it?

So yes! That´s exaclty what the webproxy does.

Using our webproxy, which means setting up the `VIRTUAL_HOST` environment you will make your domain accessible by port 80/443 and forward it to the open port (8080, 8081, 8082) of your container.

Not sure how you will set up the `/second` and `/third` option... if it is a subdomain, **second.haipham.me** and **third.haipham.me**, sure it will work as I have tested, but in that case, I have not tested yet.

Hope I was helpful somehow.

**Comment by haipham23** [comment]
Thanks @evertramos , it's quite clear now. Do I need to map the open port to the host like `docker run -d -p 8080:8080 ...` ?

**Comment by evertramos** [comment]
If you want to access by `haipham.me:8080` you must map and your connection will not be through our webproxy... but if you want to access directly from `haipham.me` you do not need to map. Actually you just add the environment option `VIRTUAL_HOST` and the webproxy will find out which port is open and forward to it.
