### ISSUE TITLE
How do I map it to a container port?

### ISSUE THREAD

**Issue by IAMtheIAM** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#35]
Hi. I followed the steps and now I see `It works!` on the domain homepage. So how do I tell it to forward this request for `mydomain.com` to port `6060` on the host?

I'm using docker swarm to host the app on port 6060.

I ran changed the path in the `.env` file to point to my nginx config. Then I  ran `./start.sh`

Finally i did 
```
docker run -d -e VIRTUAL_HOST=myprefix.westus.cloudapp.azure.com \
              -e LETSENCRYPT_HOST=myprefix.westus.cloudapp.azure.com \
              -e LETSENCRYPT_EMAIL=email@domain.com \
              --network=webproxy \
              --name my_app \
              httpd:alpine
```

So I need that request for `myprefix.westus.cloudapp.azure.com` to forward to port 6060 on the host.

Then, I will need to make `myprefix.westus.cloudapp.azure.com/dev` forward to port 6061. Where do I do that?

I saw something about `WEB_PORTS` and `VIRTUAL_PORT` but the docs are slim on them, is that the right setting?

**Comment by evertramos** [comment]
Hello @IAMtheIAM,

I have not tested on swarm yet.

Regarding the port forward, the proxy identify the open port and forward to that port, as of https://github.com/evertramos/docker-portainer-letsencrypt/blob/master/docker-compose.yml

Don't know about WEB_PORTS... please check the repos:

https://github.com/jwilder/nginx-proxy
https://github.com/jwilder/docker-gen
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
