### ISSUE TITLE
reverse proxy : redirect with specific url 

### ISSUE THREAD

**Issue by Luvgreed** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#38]
Hello again, love this tool ! 

May I know whether I can forward a request with specific url path to a specific container port using this git ?

E.g.
https://app.ABC.com/fileUpload => forward to port 5001 ( file_service ) to handle file upload
meanwhile 
https://app.ABC.com => forward to port 5000 ( bot_service ) to do the chat 

Here 's my docker compose file  :

```version: '3'
services:
      bot_service:
      image: registry.gitlab.com/liquidsky/hello_bot:v1.2
      ports:
        - 5000:80
      environment:
        - PORT=80              
        - ENV=development
        - DB_MONGO_HOST=mongodb_service
        - DB_MONGO_PORT=27017
        - DB_MONGO_NAME=bot_data       
      depends_on:
        - mongodb_service
    file_service:
      image: registry.gitlab.com/liquidsky/hello_bot:v1.0
      ports:
        - 5001:80
      depends_on:
        - bot_service
    mongodb_service:
      image: "mongo"
      container_name: mongo
```

Thank you !
ありがとうございます

**Comment by evertramos** [comment]
Hello @Luvgreed, glad you like it!

As far as I know, our proxy (built by @jwilder) only controls domain and subdomain level. If you would like to have some specific forward as menioned, `domain.com/forward` you would do that in your own app container, which would have some more controll over it.

Just a suggestion.

**Comment by Luvgreed** [comment]
No problem, thank you for your prompt reply! 👍
