### ISSUE TITLE
Missing label

### ISSUE THREAD

**Issue by treavis** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#39]
I think a label for docker gen is missing:

from letsencrypt-nginx-proxy-companion documentation:
The _com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen_ label - set this label on the docker-gen container to tell the docker-letsencrypt-nginx-proxy-companion container to use it as the docker-gen when it's split from nginx (separate containers).

**Comment by evertramos** [comment]
As of docs you only need the Environment variables:

```
environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
```

[...] Use the com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen label on the docker-gen container, **or** explicitly set the NGINX_DOCKER_GEN_CONTAINER environment variable to the name or id of that container.

Please check [here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion)
