### ISSUE TITLE
Trouble SSH proxying Apache Tomcat

### ISSUE THREAD

**Issue by IridiumMaster** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#4]
Hi, 
Very sorry to disturb you -- I have tried everything I can think of to get Tomcat 8 SSL-reverse-proxied and I'm hitting a brick wall here. I'm wondering if I'm missing something obvious or if there is a bug with the library now.
Steps to reproduce:
1. Verified that I could run the following:
docker run -it --rm -p 8888:8080 tomcat:8.0 
from here (https://hub.docker.com/_/tomcat/)
2. Modified the running tomcat container  (using the standard command sudo docker exec -i -t <name of container> /bin/bash
as follows:
a) 
https://www.n0r1sk.com/index.php/2017/07/07/nginx-reverse-proxy-with-ssl-offloading-and-apache-tomcat-backends/
Followed the above instructions, but changed 
`<Connector port="${port.prefix}1"
  URIEncoding="UTF-8"
  executor="tomcatThreadPool"
  protocol="HTTP/1.1"
  scheme="https"
  secure="true"
  proxyPort="443"
  connectionTimeout="410000"
/>`
to
`<Connector port="8443"
  URIEncoding="UTF-8"
  executor="tomcatThreadPool"
  protocol="HTTP/1.1"
  scheme="https"
  secure="true"
  proxyPort="443"
  connectionTimeout="410000"
/>
`
because the former caused Tomcat to fail to load the connector. 

b) Set up an admin / manager password using the following instructions and made sure that everything worked:
https://tecadmin.net/set-admin-password-in-tomcat/

3. Committed the tomcat container, tagging it as tomcatrunner2

4. Created an .env file as follows:
NGINX_FILES_PATH=/home/travistheadmin/docker-compose-letsencrypt-nginx-proxy-companion/myEnv

5. validated that I could run the vanilla docker-compose.yml with no issues, and made sure that certificates were generated, etc.

6. Shut down the whole service using docker-compose down

7. edited the docker-compose.yml as follows (to include tomcatrunner2:

`version: '3'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_FILES_PATH: "/home/travistheadmin/docker-compose-letsencrypt-nginx-proxy-companion/myEnv"
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      VIRTUAL_PORT: 443

  tomcat:
    image: 'tomcatrunner2'
    expose:
      - '443'
      - '80'
    environment:
       VIRTUAL_HOST: "www.mywebsite.com"
       VIRTUAL_PROTO: "https"
       VIRTUAL_PORT: "443"
       LETSENCRYPT_HOST: "www.mywebsite.com"
       LETSENCRYPT_EMAIL: "myemail@protonmail.com"`

8. Proceeded to get a "502 Bad Gateway" error for every permutation I can think of related to the above config. The logs are as follows:
_Docker version 17.06.1-ce, build 874a737
docker-compose version 1.15.0, build e12f3b9_

**NGINX ( a small sample)**
`www.myserver.com 68.13.x.y - - [02/Sep/2017:06:58:48 +0000] "GET /favicon.ico HTTP/2.0" 502 575 "https://www.myserver.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
2017/09/02 06:58:48 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 68.13.y.x, server: www.myserver.com, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.19.0.2:443/favicon.ico", host: "www.myserver.com", referrer: "https://www.myserver.com/"
`

**Proxy Companion**
`Sleep for 3600s
2017/09/02 06:58:40 Generated '/app/letsencrypt_service_data' from 2 containers
2017/09/02 06:58:40 Running '/app/update_certs'
2017/09/02 06:58:40 Watching docker events
Reloading nginx docker-gen (using separate container nginx-gen)...
2017/09/02 06:58:40 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
Reloading nginx (using separate container nginx)...
Creating/renewal www.myserver.com certificates... (www.myserver.com)
2017-09-02 06:58:41,630:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
Sleep for 3600s`

**Docker Gen:**
`2017/09/02 06:58:40 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
2017/09/02 06:58:40 Sending container 'nginx' signal '1'
2017/09/02 06:58:40 Watching docker events
2017/09/02 06:58:40 Received signal: hangup
2017/09/02 06:58:40 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2017/09/02 06:58:40 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2017/09/02 06:58:40 Received signal: hangup`

**Apache Tomcat:**
`02-Sep-2017 06:58:40.972 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.46
02-Sep-2017 06:58:40.976 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 10 2017 10:10:31 UTC
02-Sep-2017 06:58:40.977 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.46.0
02-Sep-2017 06:58:40.977 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Sep-2017 06:58:40.978 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.0-93-generic
02-Sep-2017 06:58:40.978 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Sep-2017 06:58:40.979 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-7-openjdk-amd64/jre
02-Sep-2017 06:58:40.979 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.7.0_151-b01
02-Sep-2017 06:58:40.980 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
02-Sep-2017 06:58:40.980 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
02-Sep-2017 06:58:40.981 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
02-Sep-2017 06:58:40.981 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
02-Sep-2017 06:58:40.982 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Sep-2017 06:58:40.986 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Sep-2017 06:58:40.987 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Sep-2017 06:58:40.987 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/local/tomcat/endorsed
02-Sep-2017 06:58:40.988 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
02-Sep-2017 06:58:40.988 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
02-Sep-2017 06:58:40.988 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
02-Sep-2017 06:58:40.989 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.2.12 using APR version 1.5.1.
02-Sep-2017 06:58:40.989 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
02-Sep-2017 06:58:40.996 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.1.0f  25 May 2017)
02-Sep-2017 06:58:41.288 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8443"]
02-Sep-2017 06:58:41.351 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
02-Sep-2017 06:58:41.352 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
02-Sep-2017 06:58:41.362 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1949 ms
02-Sep-2017 06:58:41.535 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
02-Sep-2017 06:58:41.550 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.46
02-Sep-2017 06:58:41.602 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/examples
02-Sep-2017 07:05:16.208 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [392,716] milliseconds.
02-Sep-2017 07:05:16.329 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/examples has finished in 394,726 ms
02-Sep-2017 07:05:16.343 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/ROOT
02-Sep-2017 07:05:16.394 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/ROOT has finished in 51 ms
02-Sep-2017 07:05:16.394 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/docs
02-Sep-2017 07:05:16.434 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/docs has finished in 40 ms
02-Sep-2017 07:05:16.435 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/host-manager
02-Sep-2017 07:05:16.490 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/host-manager has finished in 54 ms
02-Sep-2017 07:05:16.490 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/manager
02-Sep-2017 07:05:16.538 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/manager has finished in 48 ms
02-Sep-2017 07:05:16.546 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8443"]
02-Sep-2017 07:05:16.604 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
02-Sep-2017 07:05:16.665 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
02-Sep-2017 07:05:16.674 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 395311 ms`

Any help you could provide in troubleshooting would be immensely appreciated.

**Comment by kleinsasserm** [comment]
Yes, I will have a look. Did you see, that you have to modify the web.xml of your Tomcat web application too?

```
<filter>
        <filter-name>RemoteIpFilter</filter-name>
        <filter-class>org.apache.catalina.filters.RemoteIpFilter</filter-class>
        <init-param>
            <param-name>protocolHeader</param-name>
            <param-value>x-forwarded-proto</param-value>
        </init-param>
    </filter>

    <filter-mapping>
        <filter-name>RemoteIpFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
    </filter-mapping>
```
And of course I saw that we missed the nginx.conf in our blog post on n0r1sk.com. I will post the necessary configuration information here and on the n0r1sk.com blog post. But this will take some time :)

**Comment by evertramos** [comment]
Hello @IridiumMaster,

Glad @kleinsasserm can help! I do not understand much about Tomcat... as far as I saw in your `docker-compose.yml` file it that you mix things up with the `docker-compose-letsencrypt-nginx-proxy-companio`. I would suggest having to separate compose files... one for the proxy itself as of this repo and another with the services and domains.

Here is an example I have using this repo:

https://github.com/evertramos/wordpress-docker-letsencrypt

So, get this environment running, and then make your new containers, and enviornments up and running the this three containers will handle the ssl and proxy for you automatically.

Besides that I believe Mr. @kleinsasserm will have more knoledge to help you out.

Cheers!

**Comment by kleinsasserm** [comment]
In any case you have to set also the following parameters in the location part of the nginx.conf. These setttings are important as otherwise the Tomcat behind the Nginx won't get the important information and without this information the ```org.apache.catalina.filters.RemoteIpFilter``` inside the web.xml won't work. This filter will patch the request and response object inside Tomcat and therefore your code which runs inside Tomcat will get and send the correct urls. But be aware, this filter is only available in Tomcat versions > 8.0.17 I guess, so use up to date Tomcat verions

nginx location part:
```
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_pass http://your-backend;
        }
```

**Comment by IridiumMaster** [comment]
Thank you so much for your replies, gentlemen. I will try out the suggestions above and reply with the results. Cheers, Travis

**Comment by IridiumMaster** [comment]
`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial`

Ok. Validated the following: 
1) >Yes, I will have a look. Did you see, that you have to modify the web.xml of your Tomcat web >application too?
Filter was / is in place

2) Validated that I was using a later version of Tomcat
>Apache Tomcat/8.0.46

3) Altered the location section of the server block in my default.conf file for NGINX so that the server portion now reads as follows:
`server {
        server_name www.myserver.com;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES2$
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/www.myserver.com.crt;
        ssl_certificate_key /etc/nginx/certs/www.myserver.com.key;
        ssl_dhparam /etc/nginx/certs/www.myserver.com.dhparam.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass https://www.myserver.com;
        }
}
`
Launched the whole thing again via docker-compose and got another bad gateway message... Looked at the logs. The logs are as follows:

`host: "www.myserver.com"
2017/09/02 16:44:44 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 68.13.x.y, server: www.myserver.com, request: "GET /favicon.ico HTTP/2.0", upstream: "https://172.19.0.4:443/favicon.ico", host: "www.myserver.com", referrer: "https://www.myserver.com/"
www.myserver.com 68.13.x.y - - [02/Sep/2017:16:44:44 +0000] "GET /favicon.ico HTTP/2.0" 502 575 "https://www.myserver.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
`

I wondered if I had somehow corrupted the default NGINX config by fiddling previously, so I then changed my .env file to point at a new directory and relaunched, getting the following messages:

`Creating network "dockercomposeletsencryptnginxproxycompanion_default" with the default driver
Creating dockercomposeletsencryptnginxproxycompanion_tomcat_1 ... 
Creating nginx ... 
Creating nginx-letsencrypt ... 
Creating nginx-gen ... 
Creating nginx
Creating dockercomposeletsencryptnginxproxycompanion_tomcat_1
Creating nginx-gen
Creating nginx ... done`

Under the blanked new configuration, I simply got a 
"This site can’t be reached" message, however. In hindsight, I think this is because I didn't wait long enough for the config to regenerate itself. 

I shut it all down and edited the location portion of the server config per kleinsasserm's suggestion, again. Then I waited longer. I received the 502 bad gateway message again after several minutes. 

I then decided to follow evertramos' suggestion and break the config apart. 
Perhaps oddly, when I did this and ran
docker-compose -f "dockerTomcat.yml" up -d
I got a message that stated:
`WARNING: Found orphan containers (nginx-gen, nginx, nginx-letsencrypt) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating dockercomposeletsencryptnginxproxycompanion_tomcat_1 ... 
Creating dockercomposeletsencryptnginxproxycompanion_tomcat_1 ... done`

I continued to get the bad gateway message, as well, using this split configuration. Obviously, I'm still missing a piece of the puzzle. I am attaching all of my files in the hope that the picture will be clearer to both of you. Thank you again so much for taking the time to look at this.
[docker-composeYML.txt](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/files/1272336/docker-composeYML.txt)
[dockerTomcatYML.txt](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/files/1272337/dockerTomcatYML.txt)
[tomcatServerXML.txt](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/files/1272347/tomcatServerXML.txt)
[webXML.txt](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/files/1272349/webXML.txt)
[defaultConf.txt](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/files/1272350/defaultConf.txt)

Oddly, there were no logs for NGINX on the latest pass.

**Comment by kleinsasserm** [comment]
Together with my college @rauschb I can pack together a simple Nginx + Tomcat compose configuration for a single Docker host. But this will take sometime because we are normally using our border controller (https://github.com/n0r1sk) in conjunction with our Tomcat image inside swarm. So we have to will simplify  this setup and test it. Beside our normal work, this will last until the end of the next week. But maybe it can help you to find a way to solve your problem.

**Comment by IridiumMaster** [comment]
Thanks kleinsasserm. This would be tremendously helpful for me, and (I suspect, based on my informal internet searches) many others wrestling with similar issues.

**Comment by kleinsasserm** [comment]
This should do it [https://github.com/n0r1sk/https-nginx-tomcat](https://github.com/n0r1sk/https-nginx-tomcat) :smile:

**Comment by IridiumMaster** [comment]
Awesome! Was traveling today but will give it a shot tomorrow (Tuesday). Cheers!

**Comment by evertramos** [comment]
Since we did not have a reply I assume that @kleinsasserm solve the problem! Cheers!
