### ISSUE TITLE
Can not create nginx-web

### ISSUE THREAD

**Issue by boerreth** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#40]
# Error description:
Can not create and run nginx-web

# Steps to reproduce

# Expected result

# Error result
error: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (1cbf2756494a4eed28b69f8cc6a91eec3261c963e31269d75f8f3484caf3fda4): Error starting userland proxy: listen tcp x.x.x.x:443: bind: cannot assign requested address

# Comments
This is an Ubuntu 16.04 running in azure. Both port 80 and 443 is open

**Comment by alexmanno** [comment]
This seems to be the same problem reported here:
https://github.com/docker/compose/issues/3277#issuecomment-361705370

**Comment by evertramos** [comment]
Hello @boerreth,

Do you have already any services listening on port 80 or 443? If so, please stop these services and try again.

Are you really seeing the "x.x.x.x" on your log?

**Comment by boerreth** [comment]
Thanks
x.x.x.x is just my IP address. I mask it out by this.
I will check.

Is it possible to get some assistance from you to set it up on my system.
I will incorporate a couple of micro service in one solution and I need some help doing that

**Comment by evertramos** [comment]
This was an issue regarding Hyper-V and Docker, and the need/obligation of mounting the Database Path into your disk /mnt/data... you can not just use the regular path or docker volumes in this case, when using Azure servers.
