### ISSUE TITLE
503 Service Temporarily Unavailable error after all container started

### ISSUE THREAD

**Issue by gurumark** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#46]
# Error description:
I am getting 503 Service Temporarily Unavailable error accessing site through ip only

# Steps to reproduce
![screenshot from 2018-02-21 21-00-54](https://user-images.githubusercontent.com/1859151/36516089-6ab705ba-174a-11e8-918b-f00dfbdc767b.png)

I just followed the steps in the documentation:
1- started up the containers on this site. modified the .env
2- started up the container in WordPress companion
I will be happy to include any logs you request.

**Comment by evertramos** [comment]
Did you run the TEST script? Using any domain configured to you ip? Did it work?

I think this might be an issue on wordpress container not webproxy... 

Please confirm.
