### ISSUE TITLE
Is geoIP possible with your solution?

### ISSUE THREAD

**Issue by PatrikTes** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#47]
# Question
Hello, I want to use GeoIP on the site behind the proxy server, is it possible?

Thx.

**Comment by evertramos** [comment]
I think so, but you probably will need to use this settings:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/conf.d/realip.conf

**Comment by PatrikTes** [comment]
I have changed to USE_NGINX_CONF_FILES=true, restarted, but the true address is somehow still not forwarded. Maybe I have overseen something.

Thx anyway, I will search further!

**Comment by evertramos** [comment]
@PatrikTes we have some work on that to be published... but for the moment you must your the settings suggested and get the ip from the header tag 'X-Real-IP'.

Waiting on:

https://github.com/moby/moby/issues/15086

**Comment by evertramos** [comment]
This is a Moby issue at the moment.

@PatrikTes you are getting the local docker container ip right?

**Comment by PatrikTes** [comment]
Hi,

I could not continue on that at the moment, I will come back on it
tomorrow, than I will publish here when I get it running.

2018-02-23 17:38 GMT+01:00 Evert Ramos <notifications@github.com>:
