### ISSUE TITLE
Redirect requests to a port on another machine in my local network

### ISSUE THREAD

**Issue by joha78** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#51]
Thank you very much for this fabulous software. Actually it's really great and easy to use. 

Using this I get a proxy that distributes the requests to local docker containers on the same host where the docker-compose-letsencrypt-nginx-proxy-companion is running.

Do you have any hint, how I may get the proxy to distribute requests to a specific docker container (or standalone server that listens for example on port 5555) but runs on another machine?

Thank you
Jörg

**Comment by evertramos** [comment]
Well... I never tried that, but think is possible. To forward to a specific port in a container running on the host you use the option `VIRTUAL_PORT=5555` as of docs... but on another server.... here are my thoughts:

- The proxy runs the host docker sock, so, you might will need to rewrite some code to manage external hosts
- Think about security when doing that
- Proxy should be on the same network to work, in this case you could use a vpn to connect both nets


Possible, I think it is... but at the moment I don´t believe you will get it out of the box.

Here is a link for the developer of the proxy container:

https://github.com/jwilder/nginx-proxy
