### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by rodgersgb** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#52]
# Error description:
Can not get SSL to work. Using the test_start script, I've got port 80 working. When I try port 443, I get ERR_CONNECTION_REFUSED.

# Steps to reproduce
Assume my domain is: devtsaw

run: ./start.sh (nginx-web, nginx-letsencrypt, and nginx-gen all running)
run: docker run -dit -e VIRTUAL_HOST=devtsaw -e LETSENCRYPT_HOST=devtsaw --network=webproxy --name test-web httpd:alpine

# Expected result
When accessing http://devtsaw  -> It works!
When accessing https://devtsaw -> It works!

# Error result
When accessing https://devtsaw -> ERR_CONNECTION_REFUSED

# Comments
Logs from nginx-letsencrypt:

2018/03/01 18:44:27 Received event start for container 7f81283b86e5
2018/03/01 18:44:42 Debounce minTimer fired
2018/03/01 18:44:42 Generated '/app/letsencrypt_service_data' from 9 containers
2018/03/01 18:44:42 Running '/app/update_certs'
/etc/nginx/certs/devtsaw /app
Creating/renewal devtsaw certificates... (devtsaw)
2018-03-01 18:44:43,175:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
2018-03-01 18:44:44,417:INFO:simp_le:1356: Generating new account key
2018-03-01 18:44:45,200:WARNING:simp_le:1371: --email was not provided; ACME CA will have no way of contacting you.
ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: DNS name does not have enough labels

UPDATE: My domain, devtsaw, is an internal domain to my network, and after doing some research on this error I found that letsencrypt (or any public CA) can only issue certificates for valid public domain names. So, my guess is that it is failing because my domain is not passing some validity check. What if I want it to run on a private domain and my domain doesn't have to follow the public standard?

This leads me to a new question. I can generate my own certs, so can I tell nginx to use an existing cert instead of generating one? Or, can I provide my own CA (or subordinate) to sign the generated cert?

**Comment by evertramos** [comment]
Ok! Here are some comments:

- the proxy works only with letsencrypt
Sure enough you can generate your certificates and configure with nginx proxy but this repo is supposed to work with lets encrypt.

- the test container does not start port ssl, I just updated a test with ssl here it is:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/test_start_ssl.sh

- LetsEncrypt only certificates real domain name configured on public dns

So, your internal domain name will not work with letsencrypt certificates as you mentioned.
