### ISSUE TITLE
Enable Both X-Real-IP and X-Forwarded-For in realip.conf for Cloudflare

### ISSUE THREAD

**Issue by j7an** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#53]
How do I enable both X-Real-IP and X-Forwarded-For in the same realip.conf file? I would like to use X-Real-IP for Docker network IPs and use X-Forwarded-For for Cloudflare IPs.

Something like below:

```
# Please set your docker network below
# in order to forward the user real 
# ip address to your app container
set_real_ip_from  172.18.0.0/32;
real_ip_header    X-Real-IP;
real_ip_recursive on;

set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/12;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2c0f:f248::/32;
set_real_ip_from 2a06:98c0::/29;

real_ip_header X-Forwarded-For;
```

I don't think its possible to have both X-Real-IP and X-Forwarded-For in the same block. Or would X-Forwarded-For pass X-Real-IP as well? [Nginx documentation](https://nginx.org/en/docs/http/ngx_http_realip_module.html) is a little confusing.

The Cloudflare configuration is from their [site](https://support.cloudflare.com/hc/en-us/articles/200170706-How-do-I-restore-original-visitor-IP-with-Nginx-)

**Comment by j7an** [comment]
@evertramos Thanks! I will try that and post back my findings. [ServerPilot](https://serverpilot.io/community/articles/customize-nginx-settings.html)'s configuration might provide additional hints as they're using Nginx as a proxy for Apache.

**Comment by evertramos** [comment]
@j7an 

I have tested with only one option `X-Real-IP` or `X-Forwarded-For` it seems to forward the real ip to the container in the request's header. And testing with a vpn of my own it did forward the real ip to the service container, in that case the vpn ip.

I could not get both values to work together... 

Did you manage it to work? I will test it with Cloudflare over the weekend as well to see if it works.

**Comment by j7an** [comment]
@evertramos I will try the configuration later this week. Hopefully with my validation we can do a PR for Cloudflare support.

**Comment by j7an** [comment]
@evertramos Looks like I have a successful test using your suggested setup. This appears to be the same setup as Serverpilot's configuration. I have two Apache containers behind same Nginx proxy (one with Cloudflare and one without ). Both were able to detect the correct IP.

I will keep the setup running for a few days and let you know if there's any issues.
