### ISSUE TITLE
Help needed, please

### ISSUE THREAD

**Issue by gabrielfgularte** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#6]
Hi, I need some help here.

I've tried many examples but I always got the same error:
`
Unable to reach http://dev2.mixbrgames.com/.well-known/acme-challenge/quPFZRddLRSmxu5L_YjggYBXzE3LgWT3rsyGpIAJUYI: HTTPConnectionPool(host='dev2.mixbrgames.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/quPFZRddLRSmxu5L_YjggYBXzE3LgWT3rsyGpIAJUYI (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd5d7fca2d0>: Failed to establish a new connection: [Errno 111] Connection refused',))`.

I'm really desperate! Here is my `docker-compose.yml`. Could you help me to find out a solution?

```
version: '3.3'

services:

  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  database:
    container_name: mixbr-database
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  webserver:
    container_name: mixbr-nginx
    image: nginx
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=dev2.mixbrgames.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dev2.mixbrgames.com
      - LETSENCRYPT_EMAIL=gabriel@mixbrgames.com
    depends_on:
      - django
    links:
      - django

  django:
    build: .
    container_name: mixbr-django
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST
      - SITE_URL
      - EMAIL_HOST
      - EMAIL_PORT
      - LOBBY_FREE
      - LOBBY_MIN_PLAYERS
      - LOBBY_MAX_PLAYERS
      - MANAGER_ALLOWED_HOSTS
      - MATCH_MAX_ROUNDS
      - DEBUG
      - HTTP_X_FORWARDED_PROTOCOL
      - SECURE_SSL_REDIRECT
      - SECRET_KEY
    volumes:
      - ./application:/root
    depends_on:
      - database
    links:
      - database
```

Thank you!

**Comment by evertramos** [comment]
Amigo,

Você precisa criar dois arquivos... um para seu proxy e outro para seu ambiente. Depois que seu proxy estiver rodando, conforme seu arquivo, ai sim, vai rodar o docker-compose up -d do seu sistema com o django, webserver e database.

Faça e este teste e verá que vai funcionar. 

Aparentemente está tudo ok.

Aguardo retorno para fechar o _issue_.

**Comment by gabrielfgularte** [comment]
Opa!!! Obrigado! Que bom que fala português! :)

Vamos lá então, eu preciso criar uma `network` chamada `webproxy`. Depois dar o `docker-compose up` nesse seu arquivo: https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/docker-compose.yml

Depois que esse estiver rodando, eu tenho que rodar um `docker-compose up` no meu arquivo, sem os serviços de proxy:
```
version: '3.3'

services:

  database:
    container_name: mixbr-database
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  webserver:
    container_name: mixbr-nginx
    image: nginx
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=dev2.mixbrgames.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dev2.mixbrgames.com
      - LETSENCRYPT_EMAIL=gabriel@mixbrgames.com
    depends_on:
      - django
    links:
      - django

  django:
    build: .
    container_name: mixbr-django
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG
      - SECRET_KEY
    volumes:
      - ./application:/root
    depends_on:
      - database
    links:
      - database
```

É isso? Tá correto? Uma dúvida: os serviços do meu arquivo precisam estar na mesma `network` também?

**Comment by evertramos** [comment]
Fala Gabriel!

Isso ai! Todos os containers precisam estar na mesma _network_. Deve funcionar bem dessa forma, qualquer coisa avise aqui e se eu puder ajudar fico à disposição.

Aguardo confirmação.

Abs,

**Comment by gabrielfgularte** [comment]
Blz, muito obrigado pela ajuda! Como são muitas peças, acho que ainda estou longe de entender e juntar todas elas. Mas acho que estou chegando lá. Estava muito acostumado a fazer Nginx do jeito "padrão" com `sites-enabled` etc. Se você puder continuar tirando algumas dúvidas minhas vai ser ótimo!

1. Eu preciso ter um arquivo de configuração `meusite.conf` em `/etc/conf.d` como eu teria num `sites-enabled` ou o `nginx.tmpl` já faz isso e eu não preciso me preocupar com esse arquivo?

2. Outra dúvida, no `docker-compose.yml` da minha aplicação é necessário ter um serviço pro `nginx`? Vi lá nesse arquivo que vc não tem: https://github.com/evertramos/wordpress-docker-letsencrypt/blob/master/docker-compose.yml.

**Comment by evertramos** [comment]
@gabrielfgularte 

Sempre que possível e se eu souber respondo sem problemas! Creio que sou bem mais newbie que vc ai.. nunca usei o nginx a não ser nesses últimos 6 meses em produção.

Com relação à seus questionamentos:

1. Sim esse ambiente toma conta de suas configurações.

2. Sim, em cada container terá de ter ao menos um nginx ou apache padrão rodando, mas provavelmente não precisará nada mais que padrão. No caso do wordpress, uso o apache que vem com o container do wordpress não faço nenhuma configuração extra, pois o proxy já valida o certificado antes de encaminhar para o container.

Abs,

**Comment by gabrielfgularte** [comment]
Boa! Beleza! Obrigado. Vou continuar testando aqui e te dou o feedback. =D

**Comment by gabrielfgularte** [comment]
Foi!! Consegui! Muito obrigado!!!
