### ISSUE TITLE
Active error_log

### ISSUE THREAD

**Issue by babeuloula** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#60]
Hello, 

How I can active, read or access to error_log ? I've an error 400 and I don't know why. 

Thanks

**Comment by evertramos** [comment]
@babeuloula using docker you can do:

```bash
docker logs your_container_name
```

**Comment by evertramos** [comment]
@babeuloula using docker you can do:

```bash
docker logs your_container_name
```
