### ISSUE TITLE
Running virtual hosts on different ports of the same container

### ISSUE THREAD

**Issue by LorenzoCamerini** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#61]
Hi,
I am facing the problem of proxing different ports to the same container.
This is the case of Nexus Registry setup, where the nexus container exposes 8081 for nexus and a different one (i.e. 18444) for docker registry.
I have defined two sub-domain:

- nexus.mydomain.com
- docker.nexus.mydomain.com

Both of them need to use letsencrypt.
I cannot see any good solution for proxying the request coming from "nexus.mydomain.com" to 8081 and the one coming to "docker.nexus.mydomain.com" to 18444 of the same container using this proxy-companion.
I searched a bit and the only two possibile solutions could be:

- Adding an extra nginx just to have a different container that prox all request to 18444 exposed by nexus container.
- Change the nginx template in order to parse the VIRTUAL_HOST env property in order to support something like: VIRTUAL_HOSTS="nexus.mydomain.com:8081,docker.nexus.mydomain.com:18444"

The first one seems bad to me because I am introducing an extra (not wanted) nginx.
The second one seems better, but am not so confident in changing your template because I am not familiar with that syntax.

Can you give me an advice for solving my problem?
There is any possibility to support this kind of configuration in the future?

**Comment by evertramos** [comment]
Hello @LorenzoCamerini!

Thanks for your message. I am not the one who design the template, it´s designed by @jwilder (https://github.com/jwilder/nginx-proxy). 

In fact it seems you can not have two ports for the same container passing through proxy on port 80... 

The option to set the port in the domain name (domain.com:8081) seems interesting, but not sure if @jwilder will go for it, you might want to start his repo and ask him that.

In the meanwhile I think an nginx container would be very light and fast to do this jobs as you suggest. I did not thought about until I read your entire post. Nice suggestion.

If you can get it through some how let us know so we can improve our docs for future reference.

Thanks!
