### ISSUE TITLE
Swarm mode and cross network proxy reversing

### ISSUE THREAD

**Issue by xgenvn** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#63]
Hi,

I have a question about this setup:
- a.example.com -> nginx (docker-nginx) (192.168.51.111) -> (resolved to external IP) 192.168.51.122

Is it possible to have cross machine proxy reversing using docker nginx proxy?

Thanks.

**Comment by evertramos** [comment]
I did not understand your question... Could clarify, please.

**Comment by xgenvn** [comment]
@evertramos 
I meant like below setup:

![docker-nginx](https://user-images.githubusercontent.com/559443/38718244-454bb7be-3f16-11e8-94e2-116920eb281f.png)

For my understanding, it's not possible, I just want to ask if I miss something here (mostly network layer options in docker)

**Comment by thunfischbrot** [comment]
It is possible if you add another layer. The connection „External Network“ doesn‘t originate at docker-nginx, but at a service below, which can be another nginx instance (or any other reverse proxy). It‘s reverse proxies all the way down...

**Comment by evertramos** [comment]
Hello @xgenvn !

Well I have never tested that and not sure how would work using swarm as you mentioned in the question.

But as you designed I think might be possible, but the point is how you will create a docker network with another server... not sure how you will do it. 

I think might not be possible with this setting the way it was designed.

Might get some other option with traefik, I am starting a new proxy with it which will have a couple more options for settings.

**Comment by xgenvn** [comment]
@evertramos @thunfischbrot  I'll try with another service running under nginx-docker network, and resolving to external network. Thank you a lot.
