### ISSUE TITLE
Question: LetsEncrypt Certificate Renewal

### ISSUE THREAD

**Issue by chrissainty** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#67]
Hi,

Should my LetsEncrypt certificated be renewing automatically? Currently, I have to kill my container and restart it to trigger a renewal.

**Comment by thunfischbrot** [comment]
I seem to be experiencing the same. Thought it was a configuration issue, couldn't pin it down yet.

**Comment by evertramos** [comment]
Hello!

Yes, it should be renewing automatically. Could you please post the lost on your letsencrypt container, so we can see whats going on?

Thanks!

**Comment by chrissainty** [comment]
Apologies for not getting back sooner. I've checked the logs and they are full of checks for expiring certificates:

`
Creating/renewal mydomain.com certificates... (mydomain.com www.mydomain.com)
2018-05-08 20:26:46,239:INFO:simp_le:1384: Certificates already exist and renewal is not necessary, exiting with status code 1.
Sleep for 3600s
`
But I'm still receiving the email from LetsEncrypt stating the certificates are going to expire. I saw in the [JrCs repo](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) there is a command to renew certificates but that doesn't seem to work on this container. 

I know these logs don't really help with anything but I will keep an eye on them to see if anything changes.

**Comment by evertramos** [comment]
@chrissainty the logs represent the return from Lets Encrypt for the specific domain, if you keep receiving email from LE for the same domain and the container checks and mention it does not need to be renewed something is wrong... you might have a subdomain that has different certificate on it. Did you check in your browser when the ssl will expire?

**Comment by chrissainty** [comment]
I was going to check the certificate expiry but my VPS was taken down for maintenance by my hosting provider a few days ago and the certificates renewed when my containers restarted, which is frustrating. I'll maybe have to park this issue for now until my certificates come up for renewal again.

**Comment by evertramos** [comment]
ok!

Let me know when you get it back.

I will close for now, ok?

**Comment by mariuccio90** [comment]
Hi, i am experiencing the same very issue. what log would you need to
