### ISSUE TITLE
fail to enable HTTPs for GitLab CE docker

### ISSUE THREAD

**Issue by rubinliudongpo** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#70]
# Error description:
Fail to enabled HTTPS to GItLab CE Docker

# Steps to reproduce
the Gitlab CE config is as follows:
  gitlab:
    image: 'twang2218/gitlab-ce-zh:10.8.0'
    restart: always
    hostname: 'gitlab.example.com'
    depends_on:
      - gitlab-postgresql
      - gitlab-redis
    environment:
      VIRTUAL_HOST: gitlab.example.com
      LETSENCRYPT_HOST: gitlab.example.com
      LETSENCRYPT_EMAIL: xxx@xxx.com
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        external_url 'https://gitlab.example.com'
        nginx['enable'] = true
        # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
        # 比如下面的电子邮件的配置：
    ports:
      - '22:22'
    volumes:
      - ./services/gitlab/config:/etc/gitlab
      - ./services/gitlab/data:/home/git/data:Z
      - ./services/gitlab/logs:/var/log/gitlab

# Expected result
I can see http://gitlab.example.com, while fail to see https://gitlab.example.com

# Error result
I can see an error log:
2018-06-12_04:52:46.01920 nginx: [emerg] BIO_new_file("/etc/gitlab/ssl/gitlab.example.com.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/gitlab/ssl/gitlab.example.com.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

# Comments
not sure there are some more Gitlab configuration?

**Comment by evertramos** [comment]
Hello @rubinliudongpo,

Not sure about gitlab.. you must read the docs to see if there is any configuration. 

This repo only takes care of the web proxy.

If http works and https not you might want to check if your certificates was generated in `/nginx/data/certs` and your `nginx/conf.d/default.conf` file is loading this certificates. If so, you probably will need some extra config from gitlab.

Hope it helps.

**Comment by evertramos** [comment]
If you have all certificate try to add this environment option:

```bash
     - GITLAB_HTTPS=true
```

**Comment by evertramos** [comment]
@rubinliudongpo,

I got this up (not really working because redis configuration), using this repo:

https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml

Adding the env option `VITUAL_HOST` and `LETSENCRYPT_HOST`, you might want to try that. And if you could share your docker-container so we can publish as a feature of this proxy.

**Comment by steevepay** [comment]
Hi @evertramos, I made it work with a docker-compose file: Gitlab CE + Docker let's encrypt:
https://github.com/steevepay/gitlab-docker-letsencrypt

**Comment by evertramos** [comment]
Make a pull request on that I will be glad to add it. Tks
