### ISSUE TITLE
trying to enforce a http => https redirect

### ISSUE THREAD

**Issue by daithi-coombes** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#72]
# Error description:
Trying to force all http traffic to 301 to https. Looking in code I found env var `HTTPS_REDIRECT` and have set this to 'redirect'. Now requests from http redirect to https, but nginx default `502 Bad Gateway` is returned.

# Steps to reproduce

`./.env`
```
HTTPS_METHOD=redirect
```

# Expected result
All traffic from http would be routed to https

# Error result
502 Bad Gateway

# Comments

The stdout from `nginx-web`:
```
nginx-web            | example.biz 83.136.43.186 - - [19/Jun/2018:19:55:25 +0000] "GET / HTTP/2.0" 502 173 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
nginx-web            | 2018/06/19 19:55:25 [error] 9#9: *11 no live upstreams while connecting to upstream, client: 83.136.43.186, server: exqmple.biz, request: "GET / HTTP/2.0", upstream: "http://exaple.biz/", host: "example.biz"
```

The resulting `./conf.d/default.conf` file:
```
server {                                     
        server_name example.biz;
        ...
        return 301 https://$host$request_uri;
}                                                  
server {                                            
        server_name example.biz;                                        
        listen 443 ssl http2 ;                                            
        ...
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://example.biz;   // redirect loop, redirected back to 443
        }
}
```

Think this might be causing a redirect loop?

**Comment by daithi-coombes** [comment]
I'm going to close this, unless the issue reappears. Think issue was dirty container in `app` with the `VURTUAL_HOST` set as the domain name - which would explain it.

This is what I done:
 1. created my own `nignx/config.d/default.conf` to force it to work.
 2. docker system prune the vps, rebuild all containers
 3. worked but realised my custom default.conf wasn't being used - so working out of box.

I'm blaming this on a dirty container from when I was tweaking/messing with the stack ;)
closing.

**Comment by evertramos** [comment]
Hello @daithi-coombes,

The 'defsult.conf' will be overwritten and you start a new conatiner, so it will not use yours unless you set whatever option you need to (nginx.tmpl)[https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/nginx.tmpl] file.

But so far all connections I use its redirected to https...
