### ISSUE TITLE
Default network

### ISSUE THREAD

**Issue by acpower7** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#74]
I'm getting error 

`docker: Error response from daemon: network webproxy not found.`

I've had a look at the .env file and saw a default network defined, [NETWORK=webproxy](url). 

Excuse my ignorance but was wondering what this is?

I have a container running a simple static website. Are they supposed to share the same network name or something? :)

Also I'm not sure about this part

[Run the script test.sh informing your domain already configured in your DNS to point out to your server as follow:](url)

How will that script verify I am in control of the domain? What do I have to change in my DNS record for this to work?

I'm sorry if this sounds confusing but I'd appreciate if someone could help me tie all this together.

**Comment by philipkobernik** [comment]
I am not the maintainer. I think I can shed some light here from my familiarity with the library...

1. Yes, your service containers need to be attached to a network called webproxy (or other if you change the name). Yes, you need to create it.
`docker network create webproxy` will create the network. This will address the error message you described. Re-read [Starting Your Web Containers](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion#starting-your-web-containers). If you are using docker-compose with your service container, check out the wordpress docker-compose example to see how the network is specified in the docker-compose.yml file.

2. Script verified that your DNS is working by setting up a tiny test "web container." Incoming requests will arrive to your docker host addressed to "yoursite.com" as they were forwarded by your DNS settings to the IP of your docker host. The test.sh script sets up a demo service container to test that requests to yoursite.com are being handled correctly by the proxy.

3. Your DNS records should point your domain name (yoursite.com) to the IP address of your docker host using an A record. Don't forget to point "www" as well.

Hope this helps,
Philip

**Comment by acpower7** [comment]
@philipkobernik thanks for the great information!
