### ISSUE TITLE
start nginx-web

### ISSUE THREAD

**Issue by fldyown** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#75]
# Error description:
alilyun ubuntu server 16.04

# Steps to reproduce
./start.sh

# Expected result
start success

# Error result
ERROR: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (af9a1428a87e5d35a036a86e9d40dfe791767177d2729cd0ba13b11a2e122f0a): Error starting userland proxy: listen tcp **.**.**.**:443: bind: cannot assign requested address
ERROR: Encountered errors while bringing up the project.

# Comments

**Comment by evertramos** [comment]
You are using the wrong IP address in your env file. 

Test with 0.0.0.0 and you will be fine.

But I suggest finding out your real IP address which should bind service on port 80 and 443. Please note that you must have only one service listening on a port.

You can try commands like 'ifconfig' or 'ip address' in some hosting services you must add the local network ip address some other you have your real external ip address.

**Comment by mariuccio90** [comment]
I think this should be in the README.md, i am not sure i am the only one to try to put my public ip in the .env

Thanks a lot!

**Comment by evertramos** [comment]
@mariuccio90 

Thanks for your message, would you care doing a PR?

Thanks!

**Comment by fldyown** [comment]
May be firewall problem，THX
