### ISSUE TITLE
Bad display of the website after redirection by proxy

### ISSUE THREAD

**Issue by ben7244** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#76]
Thank you for this app! 

# Error description:

The proxy run, demo.kriniben.com return https://demo.kriniben.com
But the design is degraded. 
While, on the the port 8800 by the ip http://185.163.64.65:8800/ it's OK... 

`Fichier : docker-compose.yml    
       
version: '3'
services:                                                 
   php-apache:
        build:                                                    
            context: .
            dockerfile: DockerFile-apache
        links:
            - 'mariadb'
        ports:
            - "8800:80"
        environment:
            - VIRTUAL_HOST=demo.kriniben.com                       
            - LETSENCRYPT_HOST=demo.kriniben.com
            - LETSENCRYPT_EMAIL=benoit@kriniben.fr
networks:
  default:                                                  external:
      name: webproxy
`

# Steps to reproduce
http://demo.kriniben.com
Http://185.163.64.65:8800
# Expected result

A normal display

# Error result

# Comments
I try to uninstall and install many time, but the problem persist. 

Another question, why I don't see the ssl padlock on Chrome and Edge but a ! in a circle? 
Thank you!

**Comment by evertramos** [comment]
In your html you are logind the content of css files and js under http... try to use https or just use "/css/app.css" it will work. This is not an issue of the proxy.

**Comment by ben7244** [comment]
@evertramos Thank you very much!

That was the solution!

Sorry, for the pollution. I hope that will help other.
