### ISSUE TITLE
https url not working

### ISSUE THREAD

**Issue by amility** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#77]
# Error description:
I a using following docker-compose file for my containers but https url not working:

version: '2'
services:

  web-web:
    restart: always
    image: webdevops/php-nginx:7.1
    container_name: web-web
    volumes:
      - ./volumes/web/:/html/
      - ./vhost.conf:/opt/docker/etc/nginx/vhost.conf
    environment:
        - PHP_DISPLAY_ERRORS=0
        - php.error_reporting=E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
        - php.session.cookie_lifetime=86400
        - php.session.gc_maxlifetime=86400
        - PHP_MAX_EXECUTION_TIME=600
        - VIRTUAL_HOST=www.domain.net
        - LETSENCRYPT_HOST=www.domain.net
        - LETSENCRYPT_EMAIL=myemail@abcd.at
        - HTTPS_METHOD=noredirect  

  web-mysql:
    restart: always
    image: mysql:5.7
    container_name: web-mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbuser
    volumes:
      - ./volumes/mysql/:/var/lib/mysql   

networks:
  default:
    external:
      name: webproxy

If I am testing it using ./test_start_ssl.sh domain_name its working fine. But after stop test https url stop working. Please suggest solution.

# Steps to reproduce

# Expected result

# Error result

# Comments

**Comment by evertramos** [comment]
What the logs saying? Check logs for nginx-web and your container...

try to remove the `- HTTPS_METHOD=noredirect` or hit https directly, what errors comes up in browser?

**Comment by amility** [comment]
Just noticed one thing. There is no entry for listen 443 for my server in /data/conf.d/default.conf
What could be the reason? May be that's the reason its not working ?

**Comment by amility** [comment]
Problem solved mate. It was my fault. I am sorry for bothering. I uploaded wrong docker-compose file initially but after that I uploaded corrected one. But didn't know that container will not take effect until I remove and create it again LOL. But thank you so much for your reply again. Appreciate that !

**Comment by evertramos** [comment]
No problem! In this matter almost everyone is new to containers... I start a couple year ago. Good Luck! and anything else let me know. Cheers!

**Comment by amility** [comment]
Great. I appreciate your hard work. It's a very great tool for automate the things. Making life easier for people :)
