### ISSUE TITLE
Letsencrypt error

### ISSUE THREAD

**Issue by Ludea** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#8]
Hello, 

I use your docker-compose.yml and add attach 4 website with this reverse proxy.

I add
 `     VIRTUAL_HOST: YOUR_DOCMAIN.com, www.YOUR_DOCMAIN.com
       LETSENCRYPT_HOST: YOUR_DOCMAIN.com, www.YOUR_DOCMAIN.com
       LETSENCRYPT_EMAIL: YOUR_EMAIL@YOUR_DOCMAIN.com`
with my own.

But the containers give me an error, and i can not access to my websites :

`ACME server returned an error: urn:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new registration :: too many registrations for this IP`

So, I think I reach the limit.
How can I delete this or fix this issue ?
Thanks :)

**Comment by evertramos** [comment]
Did you add the options below?

```
VIRTUAL_PROTO: https
VIRTUAL_PORT: 443
```

**Comment by Ludea** [comment]
I try with add this options and not, it is same.

**Comment by Ludea** [comment]
version: '3'
services:
 app:
  build: ./site/chat
  container_name: chat
  restart: always
  environment:
  - VIRTUAL_HOST=chat.mydomain.com
  - LETSENCRYPT_HOST=chat.mydomain.com
  - LETSENCRYPT_EMAIL=webmaster@mydomain.com
  ports:
  - "3000:3000"

 nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro

 nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

 nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

 mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql

 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_HOST=mariadb
     - VIRTUAL_HOST=phpmyadmin.mydomain.com
     - LETSENCRYPT_HOST=phpmyadmin.mydomain.com
     - LETSENCRYPT_EMAIL= webmaster@mydomain.com
    restart: always
    volumes:
     - /sessions

 mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mydomain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - "$PWD/etc/:/etc/letsencrypt/"
    - "$PWD/log/:/var/log/letsencrypt/"
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

 rainloop:
  image: runningman84/rainloop
  container_name: webmail
  ports:
    - 8082:443
  environment:
    - APACHE_SERVER_NAME=webmail.mydomain.com
    - VIRTUAL_HOST=webmail.mydomain.com
    - LETSENCRYPT_HOST=webmail.mydomain.com
    - LETSENCRYPT_EMAIL= webmaster@mydomain.com

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

**Comment by Ludea** [comment]
It was a port issue, there is no need to add virtual_port and virtual_proto

**Comment by LinuxEvangelist** [comment]
I have the same problem in which way do you update the docker-compose.yml

**Comment by evertramos** [comment]
@Ludea 

Do you have two compose files?

If you have only one compose file for all these services, you might misunderstand the purpose of this repo...

It should run this repo separately and then start your services.

And I also would suggest that you use code markdown in github issued... looks better.

**Comment by Ludea** [comment]
I switch to another reverse proxy
