### ISSUE TITLE
Basic Authentication Support

### ISSUE THREAD

**Issue by teminvictus** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#80]
hi, 
not really an issue but I seem to be to stupid to get basic authentication to work.
my docker containers are working perfectly with https.
basically the question is, where do i perform the command to get authentication.
in the host machine? in nginx-web container? in my running container?

thanks for the help.

**Comment by evertramos** [comment]
@teminvictus did you read this part:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion#further-options

Open your .env file and check where you putted the NGINX_FILES_PATH.... create a htpassword folder, and then create a file named with the same VIRTUAL_HOST you have used in your sevice container, if you have "test.com,www.test.com" you just name a file "test.com".

Hope you get through.

**Comment by teminvictus** [comment]
perfect, solved my problem

**Comment by Kubilai12** [comment]
I do the commande here : https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion#further-options 

Then it s needing to restart ? cause not prompt when i go on website

**Comment by evertramos** [comment]
Hello @Kubilai12,

Yes you need to restart the nginx if you set this option after has already started the proxy. You could use the command below to do that without downtime:

```bash
$ docker exec -it nginx-web nginx -s reload
```

**Comment by Kubilai12** [comment]
Thanks so much it s good
