### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by TigPT** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#81]
# Error description:
in some php forums like SMF, some requests like uploading files I get 413 Request Entity Too Large

# Steps to reproduce
Use large urls

In conf.d/uploadsize.conf I change the value of client_max_body_size 100m; to client_max_body_size 100M; or even to 0; to disable it and I keep getting the same error?

Could the error came from the nginx behind the proxy and the proxy just relays it? changing the value dissent differs anything.

I get the error from the proxy since is the one running nginx 1.15.2, the nginx serving the files is on 1.14 and error page show 1.15.2

Is the client_max_body_size being loaded?

**Comment by TigPT** [comment]
I did docket-compose down and docker-compose up -d

Everything stayed the same.

I tried docker-compose down and the 
docker system prune
Then ./start.sh to pull and start again

It still says the same error when I try to upload a file

**Comment by TigPT** [comment]
`docker exec -it nginx-web nginx -T` doesn't show me client_max_body_size, is it suppose to?

**Comment by evertramos** [comment]
Did you enabled it on the .env file?

**Comment by TigPT** [comment]
(>ლ)
You are so patient with my issues, god bless you.

Thanks a lot, you are a life saver.
After uncomment USE_NGINX_CONF_FILES=true and relaunch with ./start.sh it was working.

(well, it started showing the same but for 1.14 (nginx of the site, not the proxy), and then it needed to change the php.ini, but it finally worked as expected)

**Comment by evertramos** [comment]
Well... if the issue is in your nginx... you add this line to your nginx conf:

https://github.com/evertramos/nignx-behind-proxy/blob/master/nignx/conf.d/default.conf#L19

Hope it helps!

God bless you too!

**Comment by ben7244** [comment]
> Did you enabled it on the .env file?
> 
> Uncomment this line in your ".env" file:
> 
> ```shell
> USE_NGINX_CONF_FILES=true
> ```
> 
> And do a compose down and up again.

Thanks guys! A great help for me!

**Comment by ben7244** [comment]
Finally that not work for me...

To soluce the problem I modified the nginx.tmpl to add `client_max_body_size 100m; ` in all `location /{} `

I don't know if it's a good practice but it's works

**Comment by evertramos** [comment]
There is not problem to add that into your location! =)

**Comment by hayzem** [comment]
FYI, creating a config file under `conf.d` is synchronized with  `nginx-data` directory. But after I removed some config files it kept the old ones in `nginx-data` and kept giving me this error.

It wold be nice to add functionality to sync properly or deleting `nginx-data` with a flag like
`./start.sh --clean`

**Comment by ingen2** [comment]
Please add environment  variable (per docker-compose project) for setting `client_max_body_size`;

docker-compose.yml file Example: 

       nginx:
       build: docker/nginx
       container_name: "myapp_nginx"
       environment:
         CLIENT_NAX_BODY_SIZE: "100m"
         VIRTUAL_HOST: "didarnet.ir"
         LETSENCRYPT_HOST: "didarnet.ir"
         LETSENCRYPT_EMAIL: "admin@didarnet.ir"
`

**Comment by youssefalaoui** [comment]
So the solution is :
- .env : uncomment or set: USE_NGINX_CONF_FILES=true
- make sure you have client_max_body_size 100m; in conf.d/uploadsize.conf
- shutdown all 3 nginx running containers: docker-compose down -v
- restart them again docker-compose up -d:
Creating nginx-web         ... done
Creating nginx-gen         ... done
Creating nginx-letsencrypt ... done

**Comment by quauhtlimtz** [comment]
> Finally that not work for me...
> 
> To soluce the problem I modified the nginx.tmpl to add `client_max_body_size 100m; ` in all `location /{} `
> 
> I don't know if it's a good practice but it's works

I had to do the same due none of the previous solutions worked for me. 

On the newest version, there is no commented "USE_NGINX_CONF_FILES=true" line in the .env file. 

Thanks.

**Comment by evertramos** [comment]
@quauhtlimtz... yes there is! 

When running the 'fresh-start.sh' script you can set the option '--use-nginx-conf-files' which will enable it just as it did in the past, but the script now is way more 'smoth' and 'smarter' then the old version. 

Wait to see the 'server-automation'... you might use it as well.

Cheers!

Thanks for your comment.
