### ISSUE TITLE
TLS Cipher Suite Update

### ISSUE THREAD

**Issue by javawolfpack** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#86]
# Error description:
Few of the TLS Cipher Suites as tested by Qualys SSL Labs are considered weak may wish to remove them from the SSL/TLS template of allowed ciphers. 
https://www.ssllabs.com/ssltest

#Comments
I may attempt to fix and submit a pull request

**Comment by javawolfpack** [comment]
It's still A+ rated overall for sites that use this companion, just potentially could be even stronger/better.

**Comment by evertramos** [comment]
We are using [nginx-web from @jwilder](https://github.com/jwilder/nginx-proxy) that uses [simp_le](https://github.com/kuba/simp_le)... so PR might be to these repos...

Thanks for the comments!

**Comment by javawolfpack** [comment]
That might make sense, will look into it... the downside of the semester about to kick off is hard to have spare time to hack on personal projects again.

**Comment by evertramos** [comment]
Just in case... add your domain without the 'www' to your dns it's not forwarding to your www.domain... cheers!

**Comment by javawolfpack** [comment]
Took me a moment to realize what you meant... put a functional link on my profile now. Domain routes correctly, think it's an NGINX + multiple subdomains issue to solve the "example.com" vs "www.example.com" issue + HTTPS redirect... Not sure if there is a simple solution.

**Comment by evertramos** [comment]
Sorry... not a native english speaker... 2 years lived in US... but I cam back 20 years ago..

and your domain is just fine now!
