### ISSUE TITLE
couldn't able to start.sh

### ISSUE THREAD

**Issue by ozzzzam** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#89]
# Error description:
couldn't able to start docker app

# Steps to reproduce

sudo ./start.sh
# Expected result

success
# Error result

```
sudo ./start.sh
Error response from daemon: network with name webproxy already exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16288  100 16288    0     0  44604      0 --:--:-- --:--:-- --:--:-- 44624
ERROR: Invalid interpolation format for "volumes" option in service "nginx-web": "${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d"
ERROR: Invalid interpolation format for "volumes" option in service "nginx-web": "${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d"

```

# Comments
 please help me to setup

**Comment by evertramos** [comment]
Hello @ozzzzam,

Thanks for testing out proxy set up.

You don´t need to use sudo to run start script. Please did you set up your .env file? Could you please share so we can look at it?

As of the logs network you are trying to use is in use somehow... please try a network with different name and try again.
