### ISSUE TITLE
How to provide host specific config ?

### ISSUE THREAD

**Issue by paulvanbladel** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#9]
Very nice sample. Thank you very much for sharing.
For a specific host i need to inject following setting.
```
proxy_http_version 1.1;
proxy_set_header Connection "";
```
I seems I can't drop things in ${NGINX_FILES_PATH}/vhost.d, because it's protected.
Is there another way to inject this?
Thanks you very much for helping me out.
Warm regards
paul.

**Comment by evertramos** [comment]
Thanks for your comment!

I am not sure how you would do that... but you could update the file nginx.tmpl in order to use this settings on your container.

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/nginx.tmpl

Hope you get through this settings.

**Comment by evertramos** [comment]
Since we did not hear any further we will close this issue. Hope you've solved.
