### ISSUE TITLE
Setting up with volume for server usage

### ISSUE THREAD

**Issue by ByteProphet** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#91]
Hello,

I want use volume for this because I don't want any files in my server host system.

In **.env**, I set volume name:

`NGINX_FILES_PATH=nginx`

In **docker-compose.yml**, just added at the end:

`volumes:
   nginx:`

I get this:

> ERROR: Named volume "nginx/conf.d:/etc/nginx/conf.d:rw" is used in service "nginx-web" but no declaration was found in the volume.

I'm not really sure that's the way to do...
Must i've use 'volume-from' or something like that?

Thanks :)

**Comment by evertramos** [comment]
Hello @ByteProphet,

Thanks for your message.

I normally don´t use volumes for this settings... so never tested.

Could your please past your .env and docker-compose file your have updated?

**Comment by evertramos** [comment]
@ByteProphet 

"**=./nginx**" you are using local... no volumes... please check.

And I found out why is not working... if you look carefully we use sub-path in volumes... so, when you use a named volume, it searches for the named volumes with full path. If you update that to have a volume for each path or one volume to keep it all (without sub-folder) it will work.

Please check:

https://github.com/moby/moby/issues/32582#issuecomment-323620743

https://stackoverflow.com/questions/38164939/can-we-mount-sub-directories-of-a-named-volume-in-docker

https://github.com/docker/compose/blob/59e96fea4f6c33dc8d49ef970bb2463f0288efda/compose/config/config.py#L321-L323
