### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by SnuppeDeluxe** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#92]
I'm so happy to found this project.
Now I transfer my nextcloud from KVM/Qemu to Docker.

The last step step for me is, to include gitea.
That's not so easy for me, but I will try it more.

**Comment by evertramos** [comment]
Welcome!

Thanks for using it.

**Comment by derek-adair** [comment]
cant emphasize thank you enough................
