### ISSUE TITLE
Potential issue with subdomains or multiple hosts

### ISSUE THREAD

**Issue by SFoskett** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#94]
# Error description:

A second SSL subdomain/host behind the reverse proxy just gives a 500 error

# Steps to reproduce

Create a SSL host (e.g. test1.example.com) and it will work. Leave it running. Create another (test2.example.com) and it will work without SSL but will give error 500 when accessed with https.

# Comments

Perhaps I'm a fool or doing something wrong, but this is definitely not working for me. I have many domains running behind the proxy with no issues but subdomains give this error. I have tried this with both manually started containers (as in the readme) and full docker-wordpress-letsencrypt compose setups.

Note that I do not see the cert in the nginx certs directory so perhaps that's the root issue. Maybe letsencrypt isn't able to create the cert for some reason.

I have tried hosts that do and do not exist in DNS with the same result.

**Comment by SFoskett** [comment]
Update: This is almost certainly an issue because docker-letsencrypt-nginx-proxy-companion always issues SAN certificates. I created e.g. test1.example.com first so it issued a SAN cert for e.g. example.com linked to that so now I'm out of luck. If I had created e.g. example.com with a cert first and then (manually?) created the certs links for test1 and test2 it probably would have worked. I'm trying that now.

**Comment by evertramos** [comment]
Hello @SFoskett...

I would like to see some logs on that to see what's wrong... I use subdomain and never had issue with that.

How does your environment looks like?

Do you have the proxy running.. and start two other containers one for each subdomain?

Can you share you compose files?

**Comment by ben7244** [comment]
If I understood your problem in your docker-compose.yml try to not place the domain at the first place.
LETSENCRYPT_HOST=www.domain.xxx,domain.com.

Have you check logs of the letsencrypt container after start or restart your app container?

**Comment by evertramos** [comment]
This issue is known about the certificates... when issue a subdomain an the container is still running, takes some time... more than usual to issue a new certificate to the root domain when added, so, we will close this as it has being working since last time I checked on #114 issue. If there is any update on that or any new errros, please reopen it.
