### ISSUE TITLE
Not issue but how to question : need to add domain without restart container. 

### ISSUE THREAD

**Issue by ben7244** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#95]
Hi! 
Actually to add a new domain to my web app container I need to restart it to run the creation of the new cert let'sencrypt.

How can I add a new domain to proxy/ssl without restart my container?

My first idea is to add a new server{} settings in data/conf.d/default.conf. But if I restart or start another container that uses the proxy. My default.conf will be reload and my settings removed... 

Thank you guys!

**Comment by evertramos** [comment]
Hello @ben7244,

If you use docker-compose, you add your domain to the VIRTUAL_HOST and restart it... no downtime:

`docker-compose restart`

=)

Give it a try!

**Comment by ben7244** [comment]
😓 I have already try that....
I will check and give news here.

**Comment by evertramos** [comment]
Have you tried:

`docker-compose create --force-recreate CONTAINER_NAME`

?

**Comment by ben7244** [comment]
Thank you @evertramos!

After docker-compose restart
Let'sEncrypt logs :
`
2018/09/16 14:53:52 Received event die for container 5c223379a47d
2018/09/16 14:53:52 Received event die for container d00e22843981
2018/09/16 14:53:53 Received event die for container c2055d3c11c5
2018/09/16 14:53:53 Received event stop for container 5c223379a47d
2018/09/16 14:53:53 Received event stop for container d00e22843981
2018/09/16 14:53:53 Received event stop for container c2055d3c11c5
2018/09/16 14:53:54 Received event start for container c2055d3c11c5
2018/09/16 14:53:54 Received event start for container 5c223379a47d
2018/09/16 14:53:55 Received event die for container 309fd3633ca8
2018/09/16 14:53:55 Received event stop for container 309fd3633ca8
2018/09/16 14:53:55 Received event start for container d00e22843981
2018/09/16 14:53:56 Received event start for container 309fd3633ca8
2018/09/16 14:54:11 Debounce minTimer fired
2018/09/16 14:54:12 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
`
After docker-compose up -d --force-recreate
It's OK! 
Certificats are renewed! 
😎

**Comment by evertramos** [comment]
Just on comment in order to do not recreate all services... depending on the size of your application you add the CONTAINER_NAME of you webserver (nginx/apache/traefik/etc) to only recreate one service.

Glad it worked!

**Comment by ben7244** [comment]
Thank you for your comment.

But for more precisions, it not the container_name that is needed but the SERVICE_NAME.

php-apache for me :
`version: '3.3'
services:                                                                   php-apache:
        image: xxxxxxxx/apache:${VERSION_APACHE}                          
        ports:                                                                      - ${PORT_APACHE}:80
        environment:
            - TZ=Europe/Paris                                                       - VIRTUAL_HOST=${URL}
            - LETSENCRYPT_HOST=${URL}                                               - LETSENCRYPT_EMAIL=xxxxx@xxxxxx.fr
            - HTTPS=${HTTPS}                                                    container_name: ${SELLER}_${CLIENT_NAME}_apache`

Thank you @evertramos! Your help is precious!

**Comment by evertramos** [comment]
sorry you are right! I miss that... I use the same name.. this is why it worked on my side, but you are right, service name!! thanks!

**Comment by evertramos** [comment]
@ben7244 

Just for the record this is the option for restarting a specific container without downtime.

```bash
docker-compose up -d --no-deps --build $CONTAINER
```

**Comment by ben7244** [comment]
Nice! Effectively with `docker-compose up -d --force-recreate` I show than a little time down was. But that was acceptable compare to `docker compose down & & docker compose up - d`

I will try that! 
Thanks for your back!
